import type { Exercise, Food, Routine } from '@/types'
import { db, DEFAULT_SETTINGS } from './index'

function food(
  id: string,
  name: string,
  nameEn: string,
  kcal: number,
  protein: number,
  fat: number,
  carbs: number,
  fiber = 0,
  barcode?: string
): Food {
  return {
    id,
    name,
    nameEn,
    barcode,
    per100g: { kcal, protein, fat, carbs, fiber },
    isCustom: false,
    createdAt: 0,
  }
}

function ex(
  id: string,
  name: string,
  nameEn: string,
  primary: Exercise['primaryMuscle'],
  secondary: Exercise['secondaryMuscles'],
  equipment: Exercise['equipment']
): Exercise {
  return {
    id,
    name,
    nameEn,
    primaryMuscle: primary,
    secondaryMuscles: secondary,
    equipment,
    isCustom: false,
  }
}

export const SEED_FOODS: Food[] = [
  food('f-chicken-breast', 'Куриная грудка', 'Chicken breast', 165, 31, 3.6, 0, 0),
  food('f-chicken-thigh', 'Куриное бедро', 'Chicken thigh', 209, 26, 10.9, 0, 0),
  food('f-turkey', 'Индейка', 'Turkey breast', 135, 30, 1, 0, 0),
  food('f-beef-lean', 'Говядина постная', 'Lean beef', 217, 26, 12, 0, 0),
  food('f-beef-mince', 'Фарш говяжий 10%', 'Ground beef 10%', 215, 26, 12, 0, 0),
  food('f-pork-loin', 'Свиная вырезка', 'Pork loin', 143, 21, 6, 0, 0),
  food('f-salmon', 'Лосось', 'Salmon', 208, 20, 13, 0, 0),
  food('f-tuna', 'Тунец консерв.', 'Tuna canned', 116, 26, 1, 0, 0),
  food('f-cod', 'Треска', 'Cod', 82, 18, 0.7, 0, 0),
  food('f-shrimp', 'Креветки', 'Shrimp', 99, 24, 0.3, 0.2, 0),
  food('f-egg', 'Яйцо куриное', 'Egg whole', 155, 13, 11, 1.1, 0),
  food('f-egg-white', 'Яичный белок', 'Egg white', 52, 11, 0.2, 0.7, 0),
  food('f-cottage', 'Творог 5%', 'Cottage cheese 5%', 121, 17, 5, 3, 0),
  food('f-cottage-low', 'Творог 0%', 'Cottage cheese 0%', 72, 16, 0.2, 1.8, 0),
  food('f-greek-yogurt', 'Греческий йогурт', 'Greek yogurt', 97, 9, 5, 3.6, 0),
  food('f-milk-2', 'Молоко 2.5%', 'Milk 2.5%', 52, 2.9, 2.5, 4.7, 0),
  food('f-whey', 'Сывороточный протеин', 'Whey protein', 400, 80, 5, 8, 0),
  food('f-casein', 'Казеин', 'Casein protein', 370, 80, 1.5, 6, 0),
  food('f-rice-white', 'Рис белый варёный', 'White rice cooked', 130, 2.7, 0.3, 28, 0.4),
  food('f-rice-brown', 'Рис бурый варёный', 'Brown rice cooked', 112, 2.3, 0.8, 24, 1.8),
  food('f-buckwheat', 'Гречка варёная', 'Buckwheat cooked', 110, 4.2, 1.1, 21, 2.7),
  food('f-oats', 'Овсянка сухая', 'Oats dry', 389, 17, 7, 66, 10.6),
  food('f-pasta', 'Макароны варёные', 'Pasta cooked', 131, 5, 1.1, 25, 1.8),
  food('f-potato', 'Картофель варёный', 'Potato boiled', 87, 1.9, 0.1, 20, 1.8),
  food('f-sweet-potato', 'Батат', 'Sweet potato', 86, 1.6, 0.1, 20, 3),
  food('f-bread-wheat', 'Хлеб пшеничный', 'Wheat bread', 265, 9, 3.2, 49, 2.7),
  food('f-bread-rye', 'Хлеб ржаной', 'Rye bread', 259, 8.5, 3.3, 48, 5.8),
  food('f-tortilla', 'Тортилья', 'Tortilla', 297, 8, 7, 50, 3),
  food('f-quinoa', 'Киноа варёная', 'Quinoa cooked', 120, 4.4, 1.9, 21, 2.8),
  food('f-banana', 'Банан', 'Banana', 89, 1.1, 0.3, 23, 2.6),
  food('f-apple', 'Яблоко', 'Apple', 52, 0.3, 0.2, 14, 2.4),
  food('f-orange', 'Апельсин', 'Orange', 47, 0.9, 0.1, 12, 2.4),
  food('f-berries', 'Ягоды микс', 'Mixed berries', 57, 0.7, 0.3, 14, 4),
  food('f-avocado', 'Авокадо', 'Avocado', 160, 2, 15, 9, 6.7),
  food('f-broccoli', 'Брокколи', 'Broccoli', 34, 2.8, 0.4, 7, 2.6),
  food('f-spinach', 'Шпинат', 'Spinach', 23, 2.9, 0.4, 3.6, 2.2),
  food('f-cucumber', 'Огурец', 'Cucumber', 16, 0.7, 0.1, 3.6, 0.5),
  food('f-tomato', 'Помидор', 'Tomato', 18, 0.9, 0.2, 3.9, 1.2),
  food('f-carrot', 'Морковь', 'Carrot', 41, 0.9, 0.2, 10, 2.8),
  food('f-onion', 'Лук', 'Onion', 40, 1.1, 0.1, 9, 1.7),
  food('f-lettuce', 'Салат листовой', 'Lettuce', 15, 1.4, 0.2, 2.9, 1.3),
  food('f-pepper', 'Перец болгарский', 'Bell pepper', 31, 1, 0.3, 6, 2.1),
  food('f-zucchini', 'Кабачок', 'Zucchini', 17, 1.2, 0.3, 3.1, 1),
  food('f-mushroom', 'Грибы', 'Mushrooms', 22, 3.1, 0.3, 3.3, 1),
  food('f-beans', 'Фасоль варёная', 'Beans cooked', 127, 8.7, 0.5, 23, 6.4),
  food('f-lentils', 'Чечевица варёная', 'Lentils cooked', 116, 9, 0.4, 20, 7.9),
  food('f-chickpeas', 'Нут варёный', 'Chickpeas cooked', 164, 8.9, 2.6, 27, 7.6),
  food('f-peanut-butter', 'Арахисовая паста', 'Peanut butter', 588, 25, 50, 20, 6),
  food('f-almonds', 'Миндаль', 'Almonds', 579, 21, 50, 22, 12.5),
  food('f-walnuts', 'Грецкий орех', 'Walnuts', 654, 15, 65, 14, 6.7),
  food('f-olive-oil', 'Оливковое масло', 'Olive oil', 884, 0, 100, 0, 0),
  food('f-butter', 'Сливочное масло', 'Butter', 717, 0.9, 81, 0.1, 0),
  food('f-coconut-oil', 'Кокосовое масло', 'Coconut oil', 862, 0, 100, 0, 0),
  food('f-honey', 'Мёд', 'Honey', 304, 0.3, 0, 82, 0.2),
  food('f-sugar', 'Сахар', 'Sugar', 387, 0, 0, 100, 0),
  food('f-dark-chocolate', 'Тёмный шоколад 70%', 'Dark chocolate 70%', 598, 7.8, 43, 46, 11),
  food('f-rice-cakes', 'Хлебцы рисовые', 'Rice cakes', 387, 8, 2.8, 82, 1.5),
  food('f-protein-bar', 'Протеиновый батончик', 'Protein bar', 360, 30, 10, 35, 5),
  food('f-cheese-hard', 'Сыр твёрдый', 'Hard cheese', 402, 25, 33, 1.3, 0),
  food('f-mozzarella', 'Моцарелла', 'Mozzarella', 280, 28, 17, 3.1, 0),
  food('f-cream-cheese', 'Сливочный сыр', 'Cream cheese', 342, 6, 34, 4, 0),
  food('f-kefir', 'Кефир 1%', 'Kefir 1%', 40, 3, 1, 4, 0),
  food('f-sour-cream', 'Сметана 15%', 'Sour cream 15%', 162, 2.6, 15, 3, 0),
  food('f-ham', 'Ветчина', 'Ham', 145, 21, 6, 1.5, 0),
  food('f-sausage', 'Сосиски', 'Sausages', 301, 12, 27, 2, 0),
  food('f-mayonnaise', 'Майонез', 'Mayonnaise', 680, 1, 75, 0.6, 0),
  food('f-ketchup', 'Кетчуп', 'Ketchup', 112, 1.7, 0.1, 26, 0.3),
  food('f-soy-sauce', 'Соевый соус', 'Soy sauce', 53, 8, 0.1, 5, 0.8),
  food('f-white-fish', 'Белая рыба', 'White fish', 96, 20, 1.5, 0, 0),
  food('f-mackerel', 'Скумбрия', 'Mackerel', 205, 19, 14, 0, 0),
  food('f-tofu', 'Тофу', 'Tofu', 76, 8, 4.8, 1.9, 0.3),
  food('f-tempeh', 'Темпе', 'Tempeh', 192, 20, 11, 8, 0),
  food('f-corn', 'Кукуруза', 'Corn', 86, 3.3, 1.4, 19, 2.7),
  food('f-peas', 'Горошек', 'Peas', 81, 5.4, 0.4, 14, 5.1),
  food('f-cabbage', 'Капуста', 'Cabbage', 25, 1.3, 0.1, 6, 2.5),
  food('f-beet', 'Свёкла', 'Beetroot', 43, 1.6, 0.2, 10, 2.8),
  food('f-pear', 'Груша', 'Pear', 57, 0.4, 0.1, 15, 3.1),
  food('f-grapes', 'Виноград', 'Grapes', 69, 0.7, 0.2, 18, 0.9),
  food('f-watermelon', 'Арбуз', 'Watermelon', 30, 0.6, 0.2, 8, 0.4),
  food('f-dates', 'Финики', 'Dates', 282, 2.5, 0.4, 75, 8),
  food('f-raisins', 'Изюм', 'Raisins', 299, 3.1, 0.5, 79, 3.7),
  food('f-cashews', 'Кешью', 'Cashews', 553, 18, 44, 30, 3.3),
  food('f-sunflower', 'Семечки подсолн.', 'Sunflower seeds', 584, 21, 51, 20, 8.6),
  food('f-flaxseed', 'Семена льна', 'Flaxseed', 534, 18, 42, 29, 27),
  food('f-chia', 'Семена чиа', 'Chia seeds', 486, 17, 31, 42, 34),
  food('f-cream', 'Сливки 20%', 'Cream 20%', 205, 2.5, 20, 3.5, 0),
  food('f-ice-cream', 'Мороженое', 'Ice cream', 207, 3.5, 11, 24, 0.7),
  food('f-pizza', 'Пицца средняя', 'Pizza average', 266, 11, 10, 33, 2.3),
  food('f-burger-bun', 'Булочка для бургера', 'Burger bun', 278, 9, 4, 51, 2),
  food('f-fries', 'Картофель фри', 'French fries', 312, 3.4, 15, 41, 3.8),
  food('f-cola', 'Кола', 'Cola', 42, 0, 0, 10.6, 0),
  food('f-juice-orange', 'Сок апельсиновый', 'Orange juice', 45, 0.7, 0.2, 10, 0.2),
  food('f-coffee', 'Кофе чёрный', 'Black coffee', 2, 0.1, 0, 0, 0),
  food('f-green-tea', 'Зелёный чай', 'Green tea', 1, 0, 0, 0, 0),
  food('f-creatine', 'Креатин (порция 5г)', 'Creatine 5g scoop', 0, 0, 0, 0, 0),
  food('f-rice-dry', 'Рис сухой', 'Rice dry', 360, 7, 0.6, 79, 1.3),
  food('f-oats-cooked', 'Овсянка варёная', 'Oatmeal cooked', 71, 2.5, 1.5, 12, 1.7),
  food('f-chicken-wing', 'Куриные крылья', 'Chicken wings', 203, 18, 14, 0, 0),
  food('f-duck', 'Утка', 'Duck', 337, 19, 28, 0, 0),
  food('f-liver', 'Печень говяжья', 'Beef liver', 135, 20, 3.6, 3.9, 0),
  food('f-jam', 'Джем', 'Jam', 278, 0.4, 0.1, 69, 1),
  food('f-maple', 'Кленовый сироп', 'Maple syrup', 260, 0, 0.1, 67, 0),
]

export const SEED_EXERCISES: Exercise[] = [
  // Chest
  ex('e-bench-press', 'Жим штанги лёжа', 'Barbell Bench Press', 'chest', ['triceps', 'shoulders'], 'barbell'),
  ex('e-incline-bench', 'Жим штанги наклон', 'Incline Barbell Bench', 'chest', ['shoulders', 'triceps'], 'barbell'),
  ex('e-decline-bench', 'Жим штанги вниз', 'Decline Bench Press', 'chest', ['triceps'], 'barbell'),
  ex('e-db-bench', 'Жим гантелей лёжа', 'Dumbbell Bench Press', 'chest', ['triceps', 'shoulders'], 'dumbbell'),
  ex('e-db-incline', 'Жим гантелей наклон', 'Incline DB Press', 'chest', ['shoulders', 'triceps'], 'dumbbell'),
  ex('e-db-fly', 'Разведение гантелей', 'Dumbbell Fly', 'chest', [], 'dumbbell'),
  ex('e-cable-fly', 'Сведение в кроссовере', 'Cable Fly', 'chest', [], 'cable'),
  ex('e-pec-deck', 'Бабочка', 'Pec Deck', 'chest', [], 'machine'),
  ex('e-push-up', 'Отжимания', 'Push-up', 'chest', ['triceps', 'shoulders'], 'bodyweight'),
  ex('e-dips-chest', 'Брусья (грудь)', 'Chest Dips', 'chest', ['triceps', 'shoulders'], 'bodyweight'),
  ex('e-machine-chest', 'Жим в тренажёре', 'Machine Chest Press', 'chest', ['triceps'], 'machine'),
  ex('e-landmine-press', 'Жим лэндмайн', 'Landmine Press', 'chest', ['shoulders'], 'barbell'),
  // Back
  ex('e-deadlift', 'Становая тяга', 'Conventional Deadlift', 'back', ['hamstrings', 'glutes', 'traps'], 'barbell'),
  ex('e-sumo-dl', 'Становая сумо', 'Sumo Deadlift', 'back', ['glutes', 'quads'], 'barbell'),
  ex('e-rdl', 'Румынская тяга', 'Romanian Deadlift', 'hamstrings', ['glutes', 'back'], 'barbell'),
  ex('e-pull-up', 'Подтягивания', 'Pull-up', 'back', ['biceps'], 'bodyweight'),
  ex('e-chin-up', 'Подтягивания обр. хват', 'Chin-up', 'back', ['biceps'], 'bodyweight'),
  ex('e-lat-pulldown', 'Тяга верхнего блока', 'Lat Pulldown', 'back', ['biceps'], 'cable'),
  ex('e-barbell-row', 'Тяга штанги в наклоне', 'Barbell Row', 'back', ['biceps'], 'barbell'),
  ex('e-db-row', 'Тяга гантели', 'One-Arm DB Row', 'back', ['biceps'], 'dumbbell'),
  ex('e-seated-row', 'Тяга горизонтальная', 'Seated Cable Row', 'back', ['biceps'], 'cable'),
  ex('e-tbar-row', 'Т-тяга', 'T-Bar Row', 'back', ['biceps'], 'barbell'),
  ex('e-face-pull', 'Face Pull', 'Face Pull', 'shoulders', ['back', 'traps'], 'cable'),
  ex('e-shrug', 'Шраги', 'Shrugs', 'traps', [], 'barbell'),
  ex('e-db-shrug', 'Шраги с гантелями', 'DB Shrugs', 'traps', [], 'dumbbell'),
  ex('e-hyperextension', 'Гиперэкстензия', 'Back Extension', 'back', ['glutes', 'hamstrings'], 'machine'),
  ex('e-straight-arm-pd', 'Тяга прямой руки', 'Straight-Arm Pulldown', 'back', [], 'cable'),
  ex('e-meadows-row', 'Тяга Meadows', 'Meadows Row', 'back', ['biceps'], 'barbell'),
  // Shoulders
  ex('e-ohp', 'Жим штанги стоя', 'Overhead Press', 'shoulders', ['triceps'], 'barbell'),
  ex('e-db-ohp', 'Жим гантелей сидя', 'Seated DB Press', 'shoulders', ['triceps'], 'dumbbell'),
  ex('e-arnold', 'Жим Арнольда', 'Arnold Press', 'shoulders', ['triceps'], 'dumbbell'),
  ex('e-lateral-raise', 'Махи в стороны', 'Lateral Raise', 'shoulders', [], 'dumbbell'),
  ex('e-front-raise', 'Махи вперёд', 'Front Raise', 'shoulders', [], 'dumbbell'),
  ex('e-rear-delt', 'Махи в наклоне', 'Rear Delt Fly', 'shoulders', [], 'dumbbell'),
  ex('e-cable-lateral', 'Махи на блоке', 'Cable Lateral Raise', 'shoulders', [], 'cable'),
  ex('e-upright-row', 'Тяга к подбородку', 'Upright Row', 'shoulders', ['traps'], 'barbell'),
  ex('e-machine-shoulder', 'Жим плеч в тренажёре', 'Machine Shoulder Press', 'shoulders', ['triceps'], 'machine'),
  ex('e-reverse-pec', 'Обратная бабочка', 'Reverse Pec Deck', 'shoulders', [], 'machine'),
  // Biceps
  ex('e-bb-curl', 'Подъём штанги на бицепс', 'Barbell Curl', 'biceps', ['forearms'], 'barbell'),
  ex('e-db-curl', 'Подъём гантелей на бицепс', 'Dumbbell Curl', 'biceps', ['forearms'], 'dumbbell'),
  ex('e-hammer-curl', 'Молотки', 'Hammer Curl', 'biceps', ['forearms'], 'dumbbell'),
  ex('e-preacher', 'Скамья Скотта', 'Preacher Curl', 'biceps', [], 'barbell'),
  ex('e-incline-curl', 'Подъём на наклонной', 'Incline DB Curl', 'biceps', [], 'dumbbell'),
  ex('e-cable-curl', 'Сгибания на блоке', 'Cable Curl', 'biceps', [], 'cable'),
  ex('e-concentration', 'Концентрированные', 'Concentration Curl', 'biceps', [], 'dumbbell'),
  ex('e-ez-curl', 'EZ-штанга на бицепс', 'EZ-Bar Curl', 'biceps', [], 'barbell'),
  // Triceps
  ex('e-close-grip', 'Жим узким хватом', 'Close-Grip Bench', 'triceps', ['chest'], 'barbell'),
  ex('e-skull-crusher', 'Французский жим', 'Skull Crusher', 'triceps', [], 'barbell'),
  ex('e-triceps-pushdown', 'Разгибания на блоке', 'Triceps Pushdown', 'triceps', [], 'cable'),
  ex('e-oh-extension', 'Разгибания из-за головы', 'Overhead Extension', 'triceps', [], 'dumbbell'),
  ex('e-dips-tri', 'Брусья (трицепс)', 'Triceps Dips', 'triceps', ['chest'], 'bodyweight'),
  ex('e-kickback', 'Кикбэк', 'Triceps Kickback', 'triceps', [], 'dumbbell'),
  ex('e-rope-pushdown', 'Разгибания канатом', 'Rope Pushdown', 'triceps', [], 'cable'),
  // Quads
  ex('e-squat', 'Приседания со штангой', 'Back Squat', 'quads', ['glutes', 'core'], 'barbell'),
  ex('e-front-squat', 'Фронтальные приседания', 'Front Squat', 'quads', ['core'], 'barbell'),
  ex('e-leg-press', 'Жим ногами', 'Leg Press', 'quads', ['glutes'], 'machine'),
  ex('e-hack-squat', 'Гакк-приседания', 'Hack Squat', 'quads', ['glutes'], 'machine'),
  ex('e-lunge', 'Выпады', 'Lunges', 'quads', ['glutes'], 'dumbbell'),
  ex('e-walking-lunge', 'Выпады в движении', 'Walking Lunges', 'quads', ['glutes'], 'dumbbell'),
  ex('e-leg-extension', 'Разгибания ног', 'Leg Extension', 'quads', [], 'machine'),
  ex('e-bulgarian', 'Болгарские сплит-приседания', 'Bulgarian Split Squat', 'quads', ['glutes'], 'dumbbell'),
  ex('e-goblet', 'Гоблет-приседания', 'Goblet Squat', 'quads', ['glutes', 'core'], 'dumbbell'),
  ex('e-leg-press-single', 'Жим одной ногой', 'Single-Leg Press', 'quads', ['glutes'], 'machine'),
  // Hamstrings
  ex('e-leg-curl', 'Сгибания ног лёжа', 'Lying Leg Curl', 'hamstrings', [], 'machine'),
  ex('e-seated-curl', 'Сгибания ног сидя', 'Seated Leg Curl', 'hamstrings', [], 'machine'),
  ex('e-db-rdl', 'Румынская с гантелями', 'DB RDL', 'hamstrings', ['glutes'], 'dumbbell'),
  ex('e-good-morning', 'Гудморнинг', 'Good Morning', 'hamstrings', ['back', 'glutes'], 'barbell'),
  ex('e-nordic', 'Nordic curl', 'Nordic Curl', 'hamstrings', [], 'bodyweight'),
  // Glutes
  ex('e-hip-thrust', 'Ягодичный мост', 'Hip Thrust', 'glutes', ['hamstrings'], 'barbell'),
  ex('e-glute-bridge', 'Мостик', 'Glute Bridge', 'glutes', [], 'bodyweight'),
  ex('e-cable-kickback', 'Отведения на блоке', 'Cable Kickback', 'glutes', [], 'cable'),
  ex('e-abduction', 'Отведения ног', 'Hip Abduction', 'glutes', [], 'machine'),
  ex('e-step-up', 'Зашагивания', 'Step-up', 'glutes', ['quads'], 'dumbbell'),
  // Calves
  ex('e-standing-calf', 'Подъёмы на носки стоя', 'Standing Calf Raise', 'calves', [], 'machine'),
  ex('e-seated-calf', 'Подъёмы на носки сидя', 'Seated Calf Raise', 'calves', [], 'machine'),
  ex('e-leg-press-calf', 'Икры в жиме ногами', 'Leg Press Calf', 'calves', [], 'machine'),
  ex('e-db-calf', 'Икры с гантелью', 'DB Calf Raise', 'calves', [], 'dumbbell'),
  // Core
  ex('e-plank', 'Планка', 'Plank', 'core', [], 'bodyweight'),
  ex('e-crunch', 'Скручивания', 'Crunch', 'core', [], 'bodyweight'),
  ex('e-hanging-leg', 'Подъём ног в висе', 'Hanging Leg Raise', 'core', [], 'bodyweight'),
  ex('e-cable-crunch', 'Скручивания на блоке', 'Cable Crunch', 'core', [], 'cable'),
  ex('e-ab-wheel', 'Ролик для пресса', 'Ab Wheel', 'core', [], 'other'),
  ex('e-russian-twist', 'Русские скручивания', 'Russian Twist', 'core', [], 'bodyweight'),
  ex('e-dead-bug', 'Dead Bug', 'Dead Bug', 'core', [], 'bodyweight'),
  ex('e-pallof', 'Pallof Press', 'Pallof Press', 'core', [], 'cable'),
  // Forearms
  ex('e-wrist-curl', 'Сгибания запястий', 'Wrist Curl', 'forearms', [], 'barbell'),
  ex('e-farmer-walk', 'Прогулка фермера', "Farmer's Walk", 'forearms', ['traps', 'core'], 'dumbbell'),
  ex('e-reverse-curl', 'Обратные сгибания', 'Reverse Curl', 'forearms', ['biceps'], 'barbell'),
  // Full body / Olympic-ish
  ex('e-clean', 'Подъём на грудь', 'Power Clean', 'full_body', ['traps', 'glutes'], 'barbell'),
  ex('e-snatch-grip-dl', 'Тяга широким хватом', 'Snatch-Grip DL', 'back', ['hamstrings'], 'barbell'),
  ex('e-thruster', 'Трастеры', 'Thruster', 'full_body', ['shoulders', 'quads'], 'barbell'),
  ex('e-kb-swing', 'Махи гирей', 'Kettlebell Swing', 'glutes', ['hamstrings', 'core'], 'kettlebell'),
  ex('e-burpee', 'Бёрпи', 'Burpee', 'full_body', [], 'bodyweight'),
  // More variety
  ex('e-incline-fly', 'Разведение наклон', 'Incline Fly', 'chest', [], 'dumbbell'),
  ex('e-floor-press', 'Жим с пола', 'Floor Press', 'chest', ['triceps'], 'barbell'),
  ex('e-pendlay', 'Тяга Пендли', 'Pendlay Row', 'back', ['biceps'], 'barbell'),
  ex('e-chest-supported-row', 'Тяга с упором', 'Chest-Supported Row', 'back', ['biceps'], 'dumbbell'),
  ex('e-y-raise', 'Y-подъёмы', 'Y-Raise', 'shoulders', [], 'dumbbell'),
  ex('e-lu-raise', 'Lu Raises', 'Lu Raises', 'shoulders', [], 'dumbbell'),
  ex('e-spider-curl', 'Паучьи сгибания', 'Spider Curl', 'biceps', [], 'dumbbell'),
  ex('e-jm-press', 'JM Press', 'JM Press', 'triceps', ['chest'], 'barbell'),
  ex('e-overhead-cable', 'Разгибания на блоке сверху', 'Cable Overhead Ext', 'triceps', [], 'cable'),
  ex('e-sissy-squat', 'Сисси-приседания', 'Sissy Squat', 'quads', [], 'bodyweight'),
  ex('e-belt-squat', 'Приседания с поясом', 'Belt Squat', 'quads', ['glutes'], 'machine'),
  ex('e-leg-curl-standing', 'Сгибания стоя', 'Standing Leg Curl', 'hamstrings', [], 'machine'),
  ex('e-45-hyper', 'Гипер 45°', '45° Hyper', 'glutes', ['hamstrings', 'back'], 'machine'),
  ex('e-donkey-calf', 'Икры «осёл»', 'Donkey Calf Raise', 'calves', [], 'machine'),
  ex('e-side-plank', 'Боковая планка', 'Side Plank', 'core', [], 'bodyweight'),
  ex('e-hanging-knee', 'Колени к груди', 'Hanging Knee Raise', 'core', [], 'bodyweight'),
  ex('e-machine-row', 'Тяга в тренажёре', 'Machine Row', 'back', ['biceps'], 'machine'),
  ex('e-smith-squat', 'Приседания в Смите', 'Smith Squat', 'quads', ['glutes'], 'machine'),
  ex('e-smith-bench', 'Жим в Смите', 'Smith Bench Press', 'chest', ['triceps'], 'machine'),
  ex('e-cable-row-single', 'Тяга одной рукой', 'Single-Arm Cable Row', 'back', ['biceps'], 'cable'),
  ex('e-pec-deck-reverse', 'Пек-дек обратный', 'Reverse Fly Machine', 'shoulders', [], 'machine'),
  ex('e-trap-bar-dl', 'Тяга с трэп-грифом', 'Trap Bar Deadlift', 'back', ['quads', 'glutes'], 'barbell'),
  ex('e-zercher', 'Зерхер-приседания', 'Zercher Squat', 'quads', ['core', 'back'], 'barbell'),
  ex('e-box-squat', 'Приседания на ящик', 'Box Squat', 'quads', ['glutes'], 'barbell'),
  ex('e-pause-squat', 'Приседания с паузой', 'Pause Squat', 'quads', ['glutes'], 'barbell'),
  ex('e-pin-press', 'Жим с пинтов', 'Pin Press', 'chest', ['triceps'], 'barbell'),
  ex('e-spoto-press', 'Spoto Press', 'Spoto Press', 'chest', ['triceps'], 'barbell'),
  ex('e-deficit-dl', 'Тяга с дефицита', 'Deficit Deadlift', 'back', ['hamstrings'], 'barbell'),
  ex('e-block-pull', 'Тяга с блоков', 'Block Pull', 'back', ['traps'], 'barbell'),
  ex('e-seal-row', 'Seal Row', 'Seal Row', 'back', ['biceps'], 'barbell'),
  ex('e-zottman', 'Сгибания Зоттмана', 'Zottman Curl', 'biceps', ['forearms'], 'dumbbell'),
  ex('e-bayesian-curl', 'Bayesian curl', 'Bayesian Curl', 'biceps', [], 'cable'),
  ex('e-crossbody-ext', 'Разгибания кроссбоди', 'Cross-body Extension', 'triceps', [], 'cable'),
  ex('e-hack-deadlift', 'Гакк-тяга', 'Hack Lift', 'quads', ['back'], 'machine'),
  ex('e-adductor', 'Сведения ног', 'Hip Adduction', 'glutes', [], 'machine'),
  ex('e-tibialis', 'Подъёмы носков на себя', 'Tibialis Raise', 'calves', [], 'other'),
  ex('e-neck-curl', 'Сгибания шеи', 'Neck Curl', 'traps', [], 'other'),
  ex('e-suitcase-carry', 'Чемодан', 'Suitcase Carry', 'core', ['forearms'], 'dumbbell'),
  ex('e-sledgehammer', 'Удары кувалдой', 'Sledgehammer', 'full_body', ['core'], 'other'),
  ex('e-battle-ropes', 'Канаты', 'Battle Ropes', 'full_body', ['shoulders'], 'other'),
  ex('e-sled-push', 'Толкание саней', 'Sled Push', 'quads', ['glutes', 'full_body'], 'other'),
  ex('e-sled-pull', 'Тяга саней', 'Sled Pull', 'back', ['hamstrings'], 'other'),
  ex('e-box-jump', 'Запрыгивания', 'Box Jump', 'quads', ['glutes'], 'bodyweight'),
  ex('e-jump-squat', 'Прыжковые приседания', 'Jump Squat', 'quads', ['glutes'], 'bodyweight'),
  ex('e-inverted-row', 'Австралийские подтягивания', 'Inverted Row', 'back', ['biceps'], 'bodyweight'),
  ex('e-diamond-pushup', 'Алмазные отжимания', 'Diamond Push-up', 'triceps', ['chest'], 'bodyweight'),
  ex('e-pike-pushup', 'Отжимания уголком', 'Pike Push-up', 'shoulders', ['triceps'], 'bodyweight'),
  ex('e-band-pullapart', 'Разведения резиной', 'Band Pull-apart', 'shoulders', ['back'], 'band'),
  ex('e-band-row', 'Тяга с резиной', 'Band Row', 'back', ['biceps'], 'band'),
  ex('e-kb-goblet', 'Гоблет с гирей', 'KB Goblet Squat', 'quads', ['glutes', 'core'], 'kettlebell'),
  ex('e-kb-press', 'Жим гири', 'KB Press', 'shoulders', ['triceps'], 'kettlebell'),
  ex('e-kb-row', 'Тяга гири', 'KB Row', 'back', ['biceps'], 'kettlebell'),
  ex('e-machine-fly', 'Сведения в тренажёре', 'Machine Fly', 'chest', [], 'machine'),
  ex('e-smith-ohp', 'Жим стоя в Смите', 'Smith OHP', 'shoulders', ['triceps'], 'machine'),
  ex('e-vbar-pulldown', 'Тяга V-грифа', 'V-Bar Pulldown', 'back', ['biceps'], 'cable'),
  ex('e-straight-bar-pd', 'Тяга прямой рукояти', 'Straight Bar Pulldown', 'back', ['biceps'], 'cable'),
  ex('e-ez-skull', 'Французский с EZ', 'EZ Skull Crusher', 'triceps', [], 'barbell'),
  ex('e-decline-crunch', 'Скручивания на наклоне', 'Decline Crunch', 'core', [], 'bodyweight'),
  ex('e-toes-to-bar', 'Носки к перекладине', 'Toes-to-Bar', 'core', [], 'bodyweight'),
  ex('e-glute-ham', 'GHD', 'Glute-Ham Raise', 'hamstrings', ['glutes'], 'machine'),
]

function buildRoutines(): Routine[] {
  const now = Date.now()
  return [
    {
      id: 'r-ppl',
      name: 'PPL (Push / Pull / Legs)',
      template: 'ppl',
      createdAt: now,
      days: [
        {
          name: 'Push',
          exerciseIds: [
            'e-bench-press',
            'e-ohp',
            'e-db-incline',
            'e-lateral-raise',
            'e-triceps-pushdown',
            'e-oh-extension',
          ],
        },
        {
          name: 'Pull',
          exerciseIds: [
            'e-deadlift',
            'e-pull-up',
            'e-barbell-row',
            'e-face-pull',
            'e-bb-curl',
            'e-hammer-curl',
          ],
        },
        {
          name: 'Legs',
          exerciseIds: [
            'e-squat',
            'e-rdl',
            'e-leg-press',
            'e-leg-curl',
            'e-leg-extension',
            'e-standing-calf',
          ],
        },
      ],
    },
    {
      id: 'r-ul',
      name: 'Upper / Lower',
      template: 'upper_lower',
      createdAt: now,
      days: [
        {
          name: 'Upper A',
          exerciseIds: [
            'e-bench-press',
            'e-barbell-row',
            'e-ohp',
            'e-lat-pulldown',
            'e-lateral-raise',
            'e-bb-curl',
            'e-triceps-pushdown',
          ],
        },
        {
          name: 'Lower A',
          exerciseIds: [
            'e-squat',
            'e-rdl',
            'e-leg-press',
            'e-leg-curl',
            'e-standing-calf',
            'e-plank',
          ],
        },
        {
          name: 'Upper B',
          exerciseIds: [
            'e-db-incline',
            'e-pull-up',
            'e-db-ohp',
            'e-seated-row',
            'e-rear-delt',
            'e-hammer-curl',
            'e-skull-crusher',
          ],
        },
        {
          name: 'Lower B',
          exerciseIds: [
            'e-deadlift',
            'e-front-squat',
            'e-bulgarian',
            'e-hip-thrust',
            'e-seated-calf',
            'e-hanging-leg',
          ],
        },
      ],
    },
    {
      id: 'r-pp',
      name: 'Push / Pull',
      template: 'push_pull',
      createdAt: now,
      days: [
        {
          name: 'Push',
          exerciseIds: [
            'e-bench-press',
            'e-ohp',
            'e-db-fly',
            'e-lateral-raise',
            'e-dips-tri',
            'e-triceps-pushdown',
          ],
        },
        {
          name: 'Pull',
          exerciseIds: [
            'e-pull-up',
            'e-barbell-row',
            'e-rdl',
            'e-face-pull',
            'e-bb-curl',
            'e-shrug',
          ],
        },
      ],
    },
    {
      id: 'r-fb',
      name: 'Full Body 3×',
      template: 'full_body',
      createdAt: now,
      days: [
        {
          name: 'Full A',
          exerciseIds: [
            'e-squat',
            'e-bench-press',
            'e-barbell-row',
            'e-ohp',
            'e-rdl',
            'e-plank',
          ],
        },
        {
          name: 'Full B',
          exerciseIds: [
            'e-deadlift',
            'e-db-incline',
            'e-pull-up',
            'e-lunge',
            'e-lateral-raise',
            'e-hanging-leg',
          ],
        },
        {
          name: 'Full C',
          exerciseIds: [
            'e-front-squat',
            'e-ohp',
            'e-seated-row',
            'e-hip-thrust',
            'e-dips-chest',
            'e-bb-curl',
          ],
        },
      ],
    },
  ]
}

export async function ensureSeeded(): Promise<void> {
  const settings = await db.settings.get('main')
  if (!settings) {
    await db.settings.put(DEFAULT_SETTINGS)
  }

  const foodCount = await db.foods.count()
  if (foodCount === 0) {
    await db.foods.bulkPut(SEED_FOODS)
  }

  const exCount = await db.exercises.count()
  if (exCount === 0) {
    await db.exercises.bulkPut(SEED_EXERCISES)
  }

  const routineCount = await db.routines.count()
  if (routineCount === 0) {
    await db.routines.bulkPut(buildRoutines())
  }
}
