import type { Exercise, Food, Routine } from '@/types'
import { db, DEFAULT_SETTINGS } from './index'

function food(
  id: string,
  name: string,
  nameEn: string,
  kcal: number,
  protein: number,
  fat: number,
  carbs: number,
  fiber = 0,
  barcode?: string
): Food {
  return {
    id,
    name,
    nameEn,
    barcode,
    per100g: { kcal, protein, fat, carbs, fiber },
    isCustom: false,
    createdAt: 0,
  }
}

function ex(
  id: string,
  name: string,
  nameEn: string,
  primary: Exercise['primaryMuscle'],
  secondary: Exercise['secondaryMuscles'],
  equipment: Exercise['equipment'],
  instructions?: string
): Exercise {
  return {
    id,
    name,
    nameEn,
    primaryMuscle: primary,
    secondaryMuscles: secondary,
    equipment,
    isCustom: false,
    ...(instructions ? { instructions } : {}),
  }
}

export const SEED_FOODS: Food[] = [
  food('f-kartofel-fri', 'Картофель фри', 'French fries', 312, 3.4, 14.7, 37.6),
  food('f-gamburger-sredniy', 'Гамбургер (средний)', 'Hamburger (medium)', 250, 12, 13, 25),
  food('f-chikenburger', 'Чикенбургер', 'Chicken burger', 260, 12, 12, 28),
  food('f-kurinye-naggetsy', 'Куриные наггетсы', 'Chicken nuggets', 290, 16, 17, 16),
  food('f-big-mak-na-100-g', 'Биг Мак (на 100 г)', 'Big Mac (per 100g)', 257, 11.8, 14.6, 20.5),
  food('f-chizburger', 'Чизбургер', 'Cheeseburger', 265, 13, 13, 27),
  food('f-kartofel-po-derevenski', 'Картофель по-деревенски', 'Potato wedges', 280, 4, 12, 38),
  food('f-lukovye-koltsa', 'Луковые кольца', 'Onion rings', 410, 4, 25, 44),
  food('f-kurinye-krylyshki', 'Куриные крылышки', 'Chicken wings', 270, 20, 18, 8),
  food('f-shaurma-kurinaya', 'Шаурма куриная', 'Chicken shawarma', 220, 12, 10, 20),
  food('f-pitstsa-margarita-na-100-g', 'Пицца Маргарита (на 100 г)', 'Margherita pizza (per 100g)', 250, 11, 10, 30),
  food('f-hot-dog', 'Хот-дог', 'Hot dog', 280, 11, 16, 24),
  food('f-kartofelnoe-pyure-fastfud', 'Картофельное пюре (фастфуд)', 'Kartofelnoe Pyure (fastfud)', 89, 1.7, 2.8, 13.4),
  food('f-sendvich-s-ryboy', 'Сэндвич с рыбой', 'Sendvich S Ryboy', 260, 11, 13, 26),
  food('f-kurinyy-strips', 'Куриный стрипс', 'Kurinyy Strips', 280, 18, 15, 15),
  food('f-burger-s-bekonom', 'Бургер с беконом', 'Burger S Bekonom', 290, 14, 17, 22),
  food('f-tvister-roll', 'Твистер / ролл', 'Tvister / Roll', 240, 11, 12, 22),
  food('f-kartofel-fri-bolshoy-na-100-g', 'Картофель фри большой (на 100 г)', 'Kartofel Fri Bolshoy (na 100 G)', 320, 3.5, 15.5, 39),
  food('f-naggetsy-sredniy', 'Наггетсы (средний)', 'Naggetsy (sredniy)', 280, 15.5, 16.5, 15.5),
  food('f-sous-barbekyu-fastfud', 'Соус барбекю (фастфуд)', 'Sous Barbekyu (fastfud)', 150, 0.5, 0.5, 36),
  food('f-ogurets-svezhiy', 'Огурец свежий', 'Cucumber fresh', 15, 0.7, 0.1, 3.6),
  food('f-kapusta-belokochannaya', 'Капуста белокочанная', 'White cabbage', 28, 1.8, 0.1, 5.4),
  food('f-kapusta-krasnokochannaya', 'Капуста краснокочанная', 'Kapusta Krasnokochannaya', 31, 1.8, 0.1, 6.1),
  food('f-kapusta-tsvetnaya', 'Капуста цветная', 'Kapusta Tsvetnaya', 30, 2.5, 0.3, 4.9),
  food('f-kapusta-brokkoli', 'Капуста брокколи', 'Broccoli', 34, 2.8, 0.4, 7),
  food('f-kapusta-pekinskaya', 'Капуста пекинская', 'Kapusta Pekinskaya', 16, 1.2, 0.2, 3.2),
  food('f-morkov', 'Морковь', 'Carrot', 35, 1.3, 0.1, 7.2),
  food('f-kartofel-syroy', 'Картофель сырой', 'Potato raw', 77, 2, 0.1, 16.3),
  food('f-kartofel-varenyy', 'Картофель варёный', 'Potato boiled', 82, 2, 0.4, 16.7),
  food('f-kabachok', 'Кабачок', 'Kabachok', 24, 0.6, 0.3, 4.6),
  food('f-tsukkini', 'Цуккини', 'Tsukkini', 17, 1.2, 0.3, 3.1),
  food('f-pomidor', 'Помидор', 'Tomato', 20, 0.9, 0.2, 3.9),
  food('f-perets-sladkiy-krasnyy', 'Перец сладкий красный', 'Perets Sladkiy Krasnyy', 27, 1.3, 0.1, 5.3),
  food('f-perets-sladkiy-zelenyy', 'Перец сладкий зелёный', 'Perets Sladkiy Zelenyy', 24, 1.3, 0.2, 5.3),
  food('f-baklazhan', 'Баклажан', 'Baklazhan', 24, 1.2, 0.1, 4.5),
  food('f-svekla', 'Свёкла', 'Svekla', 43, 1.5, 0.1, 8.8),
  food('f-redis', 'Редис', 'Redis', 20, 1.2, 0.1, 3.4),
  food('f-redka', 'Редька', 'Redka', 36, 1.9, 0.2, 6.7),
  food('f-luk-repchatyy', 'Лук репчатый', 'Luk Repchatyy', 41, 1.4, 0.2, 8.2),
  food('f-luk-zelenyy', 'Лук зелёный', 'Luk Zelenyy', 20, 1.3, 0.1, 3.2),
  food('f-chesnok', 'Чеснок', 'Chesnok', 149, 6.5, 0.5, 29.9),
  food('f-selderey', 'Сельдерей', 'Selderey', 16, 0.9, 0.1, 2.1),
  food('f-shpinat', 'Шпинат', 'Shpinat', 23, 2.9, 0.4, 3.6),
  food('f-salat-listovoy', 'Салат листовой', 'Salat Listovoy', 15, 1.4, 0.2, 2.3),
  food('f-rukkola', 'Руккола', 'Rukkola', 25, 2.6, 0.7, 3.7),
  food('f-sparzha', 'Спаржа', 'Sparzha', 20, 2.2, 0.1, 3.9),
  food('f-tykva', 'Тыква', 'Tykva', 28, 1.3, 0.1, 7.7),
  food('f-goroshek-zelenyy', 'Горошек зелёный', 'Goroshek Zelenyy', 73, 5, 0.2, 13.8),
  food('f-fasol-struchkovaya', 'Фасоль стручковая', 'Fasol Struchkovaya', 32, 2, 0.2, 4.3),
  food('f-kukuruza-sladkaya', 'Кукуруза сладкая', 'Kukuruza Sladkaya', 86, 3.3, 1.2, 19),
  food('f-bryusselskaya-kapusta', 'Брюссельская капуста', 'Bryusselskaya Kapusta', 43, 3.4, 0.3, 9),
  food('f-imbir-koren', 'Имбирь (корень)', 'Imbir (koren)', 80, 1.8, 0.8, 17.8),
  food('f-hren', 'Хрен', 'Hren', 59, 3.2, 0.4, 10.5),
  food('f-petrushka-zelen', 'Петрушка (зелень)', 'Petrushka (zelen)', 47, 3.7, 0.4, 7.6),
  food('f-ukrop', 'Укроп', 'Ukrop', 40, 2.5, 0.5, 6.3),
  food('f-bazilik', 'Базилик', 'Bazilik', 23, 3.2, 0.6, 2.7),
  food('f-yabloko', 'Яблоко', 'Apple', 47, 0.4, 0.2, 11.3),
  food('f-banan', 'Банан', 'Banana', 91, 1.5, 0.2, 22.4),
  food('f-apelsin', 'Апельсин', 'Orange', 43, 0.9, 0.1, 9),
  food('f-mandarin', 'Мандарин', 'Mandarin', 38, 0.8, 0.2, 8.1),
  food('f-grusha', 'Груша', 'Grusha', 42, 0.4, 0.1, 10.7),
  food('f-kivi', 'Киви', 'Kivi', 61, 1, 0.5, 11),
  food('f-abrikos', 'Абрикос', 'Abrikos', 44, 0.9, 0.1, 9),
  food('f-persik', 'Персик', 'Persik', 45, 0.9, 0.1, 9.5),
  food('f-sliva', 'Слива', 'Sliva', 46, 0.8, 0.3, 9.9),
  food('f-vishnya', 'Вишня', 'Vishnya', 52, 0.8, 0.2, 10.6),
  food('f-chereshnya', 'Черешня', 'Chereshnya', 52, 1.1, 0.2, 12.3),
  food('f-vinograd', 'Виноград', 'Vinograd', 69, 0.6, 0.2, 16.8),
  food('f-granat', 'Гранат', 'Granat', 52, 0.9, 0, 11.8),
  food('f-greypfrut', 'Грейпфрут', 'Greypfrut', 35, 0.7, 0.2, 6.5),
  food('f-limon', 'Лимон', 'Limon', 29, 0.9, 0.1, 3),
  food('f-laym', 'Лайм', 'Laym', 30, 0.7, 0.2, 7.7),
  food('f-ananas', 'Ананас', 'Ananas', 52, 0.4, 0.1, 11.8),
  food('f-mango', 'Манго', 'Mango', 60, 0.8, 0.4, 15),
  food('f-dynya', 'Дыня', 'Dynya', 35, 0.6, 0.3, 7.4),
  food('f-arbuz', 'Арбуз', 'Arbuz', 30, 0.6, 0.1, 5.8),
  food('f-hurma', 'Хурма', 'Hurma', 67, 0.5, 0.4, 15.3),
  food('f-inzhir-svezhiy', 'Инжир свежий', 'Inzhir Svezhiy', 54, 0.7, 0.2, 12),
  food('f-ayva', 'Айва', 'Ayva', 40, 0.6, 0.5, 8.9),
  food('f-alycha', 'Алыча', 'Alycha', 34, 0.2, 0.1, 7.9),
  food('f-nektarin', 'Нектарин', 'Nektarin', 44, 1.1, 0.3, 8.9),
  food('f-papayya', 'Папайя', 'Papayya', 43, 0.5, 0.3, 9.1),
  food('f-pomelo', 'Помело', 'Pomelo', 38, 0.8, 0, 8.6),
  food('f-feyhoa', 'Фейхоа', 'Feyhoa', 49, 1, 0.8, 10),
  food('f-guava', 'Гуава', 'Guava', 68, 2.6, 1, 8.9),
  food('f-karambola', 'Карамбола', 'Karambola', 31, 1, 0.3, 7),
  food('f-kefir-1', 'Кефир 1%', 'Kefir 1%', 40, 3, 1, 4),
  food('f-kefir-2-5', 'Кефир 2.5%', 'Kefir 2.5%', 50, 2.9, 2.5, 4),
  food('f-kefir-3-2', 'Кефир 3.2%', 'Kefir 3.2%', 56, 2.8, 3.2, 4),
  food('f-tvorog-0-obezzhirennyy', 'Творог 0% (обезжиренный)', 'Cottage cheese 0%', 71, 18, 0.6, 1.8),
  food('f-tvorog-5', 'Творог 5%', 'Cottage cheese 5%', 121, 17, 5, 1.8),
  food('f-tvorog-9', 'Творог 9%', 'Tvorog 9%', 159, 16.7, 9, 2),
  food('f-tvorog-18', 'Творог 18%', 'Tvorog 18%', 232, 14, 18, 2.8),
  food('f-yogurt-naturalnyy-1-5', 'Йогурт натуральный 1.5%', 'Yogurt Naturalnyy 1.5%', 51, 4.3, 1.5, 3.5),
  food('f-yogurt-naturalnyy-3-2', 'Йогурт натуральный 3.2%', 'Yogurt Naturalnyy 3.2%', 66, 5, 3.2, 3.5),
  food('f-ryazhenka-2-5', 'Ряженка 2.5%', 'Ryazhenka 2.5%', 54, 2.9, 2.5, 4.2),
  food('f-ryazhenka-4', 'Ряженка 4%', 'Ryazhenka 4%', 67, 2.8, 4, 4.2),
  food('f-prostokvasha-2-5', 'Простокваша 2.5%', 'Prostokvasha 2.5%', 53, 2.9, 2.5, 4.1),
  food('f-smetana-10', 'Сметана 10%', 'Smetana 10%', 115, 3, 10, 2.9),
  food('f-smetana-15', 'Сметана 15%', 'Smetana 15%', 160, 2.9, 15, 3),
  food('f-smetana-20', 'Сметана 20%', 'Smetana 20%', 206, 2.8, 20, 3.2),
  food('f-smetana-30', 'Сметана 30%', 'Smetana 30%', 294, 2.4, 30, 3.1),
  food('f-moloko-0-5', 'Молоко 0.5%', 'Moloko 0.5%', 35, 3, 0.5, 4.8),
  food('f-moloko-1-5', 'Молоко 1.5%', 'Moloko 1.5%', 45, 3, 1.5, 4.8),
  food('f-moloko-2-5', 'Молоко 2.5%', 'Moloko 2.5%', 54, 2.9, 2.5, 4.8),
  food('f-moloko-3-2', 'Молоко 3.2%', 'Moloko 3.2%', 60, 2.9, 3.2, 4.7),
  food('f-slivki-10', 'Сливки 10%', 'Slivki 10%', 119, 2.7, 10, 4.4),
  food('f-slivki-20', 'Сливки 20%', 'Slivki 20%', 205, 2.5, 20, 4),
  food('f-syr-tvorozhnyy', 'Сыр творожный', 'Cream cheese', 245, 6.5, 22.7, 3.6),
  food('f-syr-plavlenyy', 'Сыр плавленый', 'Processed cheese', 300, 20.5, 23, 2.5),
  food('f-syr-knyaz-vladimir', 'Сыр Князь Владимир', 'Knyaz Vladimir cheese', 310, 24, 23, 0),
  food('f-syr-chernyy-prints', 'Сыр Черный принц', 'Chernyy Prints cheese', 328, 25.2, 22, 0),
  food(
    'f-syr-halumi-dlya-zharki-klassicheskiy',
    'Сыр халуми для жарки классический',
    'Halloumi for frying classic',
    355,
    16,
    25,
    2.6
  ),
  food('f-bifidok', 'Бифидок', 'Bifidok', 52, 2.9, 2.5, 4),
  food('f-grechka-varenaya', 'Гречка варёная', 'Buckwheat cooked', 110, 4.2, 1.1, 21.3),
  food('f-grechka-suhaya', 'Гречка сухая', 'Grechka Suhaya', 313, 12.6, 3.3, 62.1),
  food('f-ris-belyy-varenyy', 'Рис белый варёный', 'White rice cooked', 130, 2.4, 0.2, 28),
  food('f-ris-belyy-suhoy', 'Рис белый сухой', 'Ris Belyy Suhoy', 344, 6.7, 0.7, 78.9),
  food('f-ris-buryy-varenyy', 'Рис бурый варёный', 'Ris Buryy Varenyy', 111, 2.6, 0.9, 23),
  food('f-ovsyanka-na-vode', 'Овсянка на воде', 'Oatmeal on water', 88, 3, 1.7, 15),
  food('f-ovsyanye-hlopya-suhie', 'Овсяные хлопья сухие', 'Ovsyanye Hlopya Suhie', 352, 12.3, 6.2, 61.8),
  food('f-perlovka-varenaya', 'Перловка варёная', 'Perlovka Varenaya', 109, 3.1, 0.4, 23),
  food('f-perlovka-suhaya', 'Перловка сухая', 'Perlovka Suhaya', 320, 9.3, 1.1, 73.7),
  food('f-psheno-varenoe', 'Пшено варёное', 'Psheno Varenoe', 90, 3, 0.7, 17),
  food('f-psheno-suhoe', 'Пшено сухое', 'Psheno Suhoe', 348, 11.5, 3.3, 69.3),
  food('f-mannaya-krupa-suhaya', 'Манная крупа сухая', 'Mannaya Krupa Suhaya', 328, 10.3, 1, 67.4),
  food('f-mannaya-kasha-na-vode', 'Манная каша на воде', 'Mannaya Kasha Na Vode', 80, 2.5, 0.2, 16.8),
  food('f-kukuruznaya-krupa-suhaya', 'Кукурузная крупа сухая', 'Kukuruznaya Krupa Suhaya', 337, 8.3, 1.2, 75),
  food('f-yachnevaya-krupa-suhaya', 'Ячневая крупа сухая', 'Yachnevaya Krupa Suhaya', 324, 10, 1.3, 66.3),
  food('f-bulgur-varenyy', 'Булгур варёный', 'Bulgur Varenyy', 83, 3.1, 0.2, 19),
  food('f-kinoa-varenaya', 'Киноа варёная', 'Kinoa Varenaya', 120, 4.4, 1.9, 21),
  food('f-chechevitsa-varenaya', 'Чечевица варёная', 'Chechevitsa Varenaya', 116, 9, 0.4, 20),
  food('f-fasol-varenaya', 'Фасоль варёная', 'Fasol Varenaya', 123, 9, 0.5, 21),
  food('f-nut-varenyy', 'Нут варёный', 'Nut Varenyy', 164, 9, 2.6, 27),
  food('f-goroh-varenyy', 'Горох варёный', 'Goroh Varenyy', 60, 6, 0.4, 9),
  food('f-gerkules-suhoy', 'Геркулес сухой', 'Gerkules Suhoy', 352, 12.5, 6.2, 61),
  food('f-makarony-varenye', 'Макароны варёные', 'Pasta cooked', 112, 3.5, 0.4, 23),
  food('f-spagetti-varenye', 'Спагетти варёные', 'Spagetti Varenye', 130, 5, 0.8, 25),
  food('f-makarony-suhie', 'Макароны сухие', 'Makarony Suhie', 340, 10.5, 1.1, 71),
  food('f-makarony-iz-tverdyh-sortov-suhie', 'Макароны из твёрдых сортов сухие', 'Makarony Iz Tverdyh Sortov Suhie', 338, 11, 1.3, 70.5),
  food('f-lapsha-yaichnaya-suhaya', 'Лапша яичная сухая', 'Lapsha Yaichnaya Suhaya', 345, 12, 2.5, 68),
  food('f-lapsha-varenaya', 'Лапша варёная', 'Lapsha Varenaya', 138, 4.5, 0.6, 25),
  food('f-fettuchini-varenye', 'Феттучини варёные', 'Fettuchini Varenye', 142, 5, 1, 26),
  food('f-penne-varenye', 'Пенне варёные', 'Penne Varenye', 126, 4.5, 0.5, 24.5),
  food('f-rozhki-varenye', 'Рожки варёные', 'Rozhki Varenye', 115, 3.8, 0.4, 23.5),
  food('f-vermishel-suhaya', 'Вермишель сухая', 'Vermishel Suhaya', 340, 10.4, 1.1, 71.5),
  food('f-pasta-tselnozernovaya-varenaya', 'Паста цельнозерновая варёная', 'Pasta Tselnozernovaya Varenaya', 124, 5, 0.8, 26),
  food('f-hleb-belyy', 'Хлеб белый', 'White bread', 265, 8, 3.2, 49),
  food('f-hleb-rzhanoy', 'Хлеб ржаной', 'Rye bread', 214, 6, 1, 42),
  food('f-hleb-tselnozernovoy', 'Хлеб цельнозерновой', 'Hleb Tselnozernovoy', 247, 9, 3, 41),
  food('f-hleb-borodinskiy', 'Хлеб бородинский', 'Hleb Borodinskiy', 208, 6.9, 1.3, 40.9),
  food('f-baton-nareznoy', 'Батон нарезной', 'Baton Nareznoy', 264, 8, 3, 51),
  food('f-lavash-tonkiy', 'Лаваш тонкий', 'Lavash Tonkiy', 236, 8, 1, 48),
  food('f-baget', 'Багет', 'Baget', 270, 9, 1.5, 54),
  food('f-bulochka-sdobnaya', 'Булочка сдобная', 'Bulochka Sdobnaya', 300, 7.5, 5, 55),
  food('f-suhari-pshenichnye', 'Сухари пшеничные', 'Suhari Pshenichnye', 390, 11, 5, 72),
  food('f-sushki', 'Сушки', 'Sushki', 330, 11, 1.3, 73),
  food('f-baranki', 'Баранки', 'Baranki', 314, 10.4, 1.3, 68.7),
  food('f-kruassan', 'Круассан', 'Kruassan', 406, 8, 21, 46),
  food('f-bliny', 'Блины', 'Bliny', 186, 6, 5, 28),
  food('f-oladi', 'Оладьи', 'Oladi', 210, 6, 8, 28),
  food('f-pirozhok-s-kapustoy', 'Пирожок с капустой', 'Pirozhok S Kapustoy', 220, 5, 8, 32),
  food('f-hlebtsy-risovye', 'Хлебцы рисовые', 'Hlebtsy Risovye', 350, 7, 1.5, 78),
  food('f-hlebtsy-pshenichnye', 'Хлебцы пшеничные', 'Hlebtsy Pshenichnye', 320, 10, 2, 65),
  food('f-suhariki', 'Сухарики', 'Suhariki', 380, 10, 6, 70),
  food('f-pechene-ovsyanoe', 'Печенье овсяное', 'Pechene Ovsyanoe', 437, 7, 15, 71),
  food('f-galety', 'Галеты', 'Galety', 390, 9, 10, 68),
  food('f-govyadina-postnaya', 'Говядина постная', 'Lean beef', 187, 22, 10, 0),
  food('f-govyadina-1-kategorii', 'Говядина 1 категории', 'Govyadina 1 Kategorii', 218, 18.6, 16, 0),
  food('f-govyadina-2-kategorii', 'Говядина 2 категории', 'Govyadina 2 Kategorii', 168, 20, 9.8, 0),
  food('f-govyadina-vyrezka', 'Говядина вырезка', 'Govyadina Vyrezka', 158, 22, 7, 0),
  food('f-svinina-nezhirnaya', 'Свинина нежирная', 'Svinina Nezhirnaya', 242, 20, 18, 0),
  food('f-svinina-myasnaya', 'Свинина мясная', 'Svinina Myasnaya', 357, 14.3, 33.3, 0),
  food('f-svinina-zhirnaya', 'Свинина жирная', 'Svinina Zhirnaya', 489, 11.4, 49.3, 0),
  food('f-svinina-vyrezka', 'Свинина вырезка', 'Svinina Vyrezka', 142, 19.4, 7.1, 0),
  food('f-baranina', 'Баранина', 'Baranina', 209, 17, 16, 0),
  food('f-baranina-postnaya', 'Баранина постная', 'Baranina Postnaya', 166, 19.8, 9.6, 0),
  food('f-telyatina', 'Телятина', 'Telyatina', 97, 20, 1.5, 0),
  food('f-krolik', 'Кролик', 'Krolik', 156, 21, 8, 0),
  food('f-konina', 'Конина', 'Konina', 143, 20.2, 7, 0),
  food('f-pechen-govyazhya', 'Печень говяжья', 'Pechen Govyazhya', 127, 17.9, 3.7, 5.3),
  food('f-pechen-svinaya', 'Печень свиная', 'Pechen Svinaya', 109, 18.8, 3.6, 4.7),
  food('f-serdtse-govyazhe', 'Сердце говяжье', 'Serdtse Govyazhe', 96, 16, 3.5, 0),
  food('f-yazyk-govyazhiy', 'Язык говяжий', 'Yazyk Govyazhiy', 173, 16, 12.1, 0),
  food('f-farsh-govyazhiy', 'Фарш говяжий', 'Farsh Govyazhiy', 254, 17, 20, 0),
  food('f-farsh-svinoy', 'Фарш свиной', 'Farsh Svinoy', 263, 17, 21, 0),
  food('f-farsh-smeshannyy', 'Фарш смешанный', 'Farsh Smeshannyy', 250, 16, 20, 0),
  food('f-kurinaya-grudka-varenaya', 'Куриная грудка (варёная)', 'Chicken breast boiled', 165, 31, 3.6, 0),
  food('f-kurinaya-grudka-syraya', 'Куриная грудка сырая', 'Chicken breast raw', 113, 23.6, 1.9, 0),
  food('f-kurinoe-bedro-bez-kozhi', 'Куриное бедро без кожи', 'Kurinoe Bedro Bez Kozhi', 185, 21, 11, 0),
  food('f-kurinoe-bedro-s-kozhey', 'Куриное бедро с кожей', 'Kurinoe Bedro S Kozhey', 210, 18, 15, 0),
  food('f-kuritsa-srednee', 'Курица (среднее)', 'Kuritsa (srednee)', 170, 20, 9, 0),
  food('f-kurinaya-golen', 'Куриная голень', 'Kurinaya Golen', 180, 19, 11, 0),
  food('f-indeyka-grudka', 'Индейка грудка', 'Indeyka Grudka', 135, 30, 1, 0),
  food('f-indeyka-srednee', 'Индейка (среднее)', 'Indeyka (srednee)', 189, 21, 12, 0),
  food('f-utka', 'Утка', 'Utka', 248, 16, 20, 0),
  food('f-gus', 'Гусь', 'Gus', 364, 16, 33, 0),
  food('f-kurinaya-pechen', 'Куриная печень', 'Kurinaya Pechen', 137, 17, 6, 1.4),
  food('f-tsyplenok-broyler', 'Цыплёнок-бройлер', 'Tsyplenok-broyler', 160, 18.5, 9, 0),
  food('f-file-indeyki', 'Филе индейки', 'File Indeyki', 110, 24, 1, 0),
  food('f-krylya-kurinye', 'Крылья куриные', 'Krylya Kurinye', 200, 18, 14, 0),
  food('f-gorbusha', 'Горбуша', 'Gorbusha', 147, 21, 7, 0),
  food('f-treska', 'Треска', 'Cod', 82, 18, 0.7, 0),
  food('f-mintay', 'Минтай', 'Mintay', 72, 16, 0.9, 0),
  food('f-skumbriya', 'Скумбрия', 'Skumbriya', 191, 18, 13, 0),
  food('f-losos-semga', 'Лосось / сёмга', 'Salmon', 208, 20, 13, 0),
  food('f-forel', 'Форель', 'Forel', 141, 20, 6, 0),
  food('f-seld', 'Сельдь', 'Seld', 158, 18, 9, 0),
  food('f-tunets', 'Тунец', 'Tunets', 132, 28, 1, 0),
  food('f-sudak', 'Судак', 'Sudak', 97, 21, 1.3, 0),
  food('f-schuka', 'Щука', 'Schuka', 84, 18.4, 0.8, 0),
  food('f-karp', 'Карп', 'Karp', 112, 16, 5.3, 0),
  food('f-sazan', 'Сазан', 'Sazan', 121, 18.4, 5.3, 0),
  food('f-hek', 'Хек', 'Hek', 86, 16.6, 2.2, 0),
  food('f-kambala', 'Камбала', 'Kambala', 90, 15.7, 3, 0),
  food('f-krevetki', 'Креветки', 'Krevetki', 99, 21, 1.7, 0),
  food('f-kalmar', 'Кальмар', 'Kalmar', 92, 18, 2, 0),
  food('f-krab', 'Краб', 'Krab', 87, 18, 1.1, 0),
  food('f-midii', 'Мидии', 'Midii', 77, 11.5, 2, 3.3),
  food('f-ikra-krasnaya', 'Икра красная', 'Ikra Krasnaya', 250, 32, 15, 0),
  food('f-ikra-chernaya', 'Икра чёрная', 'Ikra Chernaya', 235, 26, 14, 0),
  food('f-govyadina-tushenaya', 'Говядина тушёная', 'Govyadina Tushenaya', 220, 16.8, 17, 0.2),
  food('f-svinina-tushenaya', 'Свинина тушёная', 'Svinina Tushenaya', 349, 14.9, 32.2, 0),
  food('f-gorbusha-naturalnaya', 'Горбуша натуральная', 'Gorbusha Naturalnaya', 138, 20.9, 5.8, 0),
  food('f-sayra-v-masle', 'Сайра в масле', 'Sayra V Masle', 250, 18, 20, 0),
  food('f-shproty-v-masle', 'Шпроты в масле', 'Shproty V Masle', 360, 17, 32, 0),
  food('f-skumbriya-v-masle', 'Скумбрия в масле', 'Skumbriya V Masle', 280, 15, 25, 0),
  food('f-tunets-v-sobstvennom-soku', 'Тунец в собственном соку', 'Tunets V Sobstvennom Soku', 100, 22, 1, 0),
  food('f-tunets-v-masle', 'Тунец в масле', 'Tunets V Masle', 190, 19, 12, 0),
  food('f-pechen-treski', 'Печень трески', 'Pechen Treski', 613, 4.2, 65.7, 1.2),
  food('f-pashtet-myasnoy', 'Паштет мясной', 'Pashtet Myasnoy', 300, 10, 28, 2),
  food('f-pashtet-pechenochnyy', 'Паштет печёночный', 'Pashtet Pechenochnyy', 320, 11, 30, 1.5),
  food('f-zavtrak-turista-govyadina', 'Завтрак туриста (говядина)', 'Zavtrak Turista (govyadina)', 176, 20.5, 10.4, 0),
  food('f-zavtrak-turista-svinina', 'Завтрак туриста (свинина)', 'Zavtrak Turista (svinina)', 206, 16.9, 15.4, 0),
  food('f-kilka-v-tomate', 'Килька в томате', 'Kilka V Tomate', 160, 12, 9, 6),
  food('f-bychki-v-tomate', 'Бычки в томате', 'Bychki V Tomate', 145, 12.8, 8.1, 5.2),
  food('f-goroshek-zelenyy-konservirovannyy', 'Горошек зелёный консервированный', 'Goroshek Zelenyy Konservirovannyy', 55, 3.6, 0.1, 9.8),
  food('f-kukuruza-konservirovannaya', 'Кукуруза консервированная', 'Kukuruza Konservirovannaya', 58, 2.2, 0.4, 11.2),
  food('f-fasol-konservirovannaya', 'Фасоль консервированная', 'Fasol Konservirovannaya', 70, 4.5, 0.3, 12),
  food('f-klubnika', 'Клубника', 'Klubnika', 32, 0.7, 0.3, 7.7),
  food('f-chernika', 'Черника', 'Chernika', 40, 1.1, 0.4, 8.6),
  food('f-malina', 'Малина', 'Malina', 41, 0.8, 0.5, 9),
  food('f-klyukva', 'Клюква', 'Klyukva', 28, 0.5, 0.2, 4.8),
  food('f-smorodina-chernaya', 'Смородина чёрная', 'Smorodina Chernaya', 40, 1, 0.2, 8),
  food('f-smorodina-krasnaya', 'Смородина красная', 'Smorodina Krasnaya', 38, 0.6, 0.2, 7.7),
  food('f-smorodina-belaya', 'Смородина белая', 'Smorodina Belaya', 39, 0.5, 0.2, 8),
  food('f-brusnika', 'Брусника', 'Brusnika', 43, 0.7, 0.5, 9.6),
  food('f-ezhevika', 'Ежевика', 'Ezhevika', 34, 1.5, 0.5, 4.4),
  food('f-golubika', 'Голубика', 'Golubika', 39, 1, 0.5, 6.6),
  food('f-kryzhovnik', 'Крыжовник', 'Kryzhovnik', 45, 0.7, 0.2, 9.1),
  food('f-oblepiha', 'Облепиха', 'Oblepiha', 82, 1.2, 5.4, 5.7),
  food('f-moroshka', 'Морошка', 'Moroshka', 40, 0.8, 0.9, 7.4),
  food('f-zemlyanika', 'Земляника', 'Zemlyanika', 41, 0.8, 0.4, 7.5),
  food('f-ryabina-krasnaya', 'Рябина красная', 'Ryabina Krasnaya', 50, 1.4, 0.2, 8.9),
  food('f-ryabina-chernoplodnaya', 'Рябина черноплодная', 'Ryabina Chernoplodnaya', 55, 1.5, 0.2, 10.9),
  food('f-kalina', 'Калина', 'Kalina', 26, 0.4, 0.2, 6.5),
  food('f-shipovnik-svezhiy', 'Шиповник свежий', 'Shipovnik Svezhiy', 51, 1.6, 0, 10),
  food('f-barbaris', 'Барбарис', 'Barbaris', 29, 0, 0, 7.9),
  food('f-zhimolost', 'Жимолость', 'Zhimolost', 41, 0, 0, 8.5),
  food('f-sok-yablochnyy', 'Сок яблочный', 'Sok Yablochnyy', 46, 0.1, 0.1, 11.3),
  food('f-sok-apelsinovyy', 'Сок апельсиновый', 'Sok Apelsinovyy', 45, 0.7, 0.2, 10.4),
  food('f-sok-tomatnyy', 'Сок томатный', 'Sok Tomatnyy', 20, 1, 0.1, 3.8),
  food('f-sok-vinogradnyy', 'Сок виноградный', 'Sok Vinogradnyy', 54, 0.3, 0, 14),
  food('f-sok-vishnevyy', 'Сок вишнёвый', 'Sok Vishnevyy', 47, 0.5, 0, 10.6),
  food('f-sok-persikovyy', 'Сок персиковый', 'Sok Persikovyy', 50, 0.5, 0.1, 12),
  food('f-sok-ananasovyy', 'Сок ананасовый', 'Sok Ananasovyy', 48, 0.3, 0.1, 11.5),
  food('f-sok-greypfrutovyy', 'Сок грейпфрутовый', 'Sok Greypfrutovyy', 38, 0.5, 0.1, 8),
  food('f-sok-morkovnyy', 'Сок морковный', 'Sok Morkovnyy', 40, 1, 0.1, 9),
  food('f-sok-granatovyy', 'Сок гранатовый', 'Sok Granatovyy', 56, 0.5, 0, 14),
  food('f-nektar-multifruktovyy', 'Нектар мультифруктовый', 'Nektar Multifruktovyy', 48, 0.3, 0.1, 11.5),
  food('f-sok-iz-chernoy-smorodiny', 'Сок из чёрной смородины', 'Sok Iz Chernoy Smorodiny', 50, 0.5, 0.1, 12),
  food('f-pelmeni-srednie', 'Пельмени (средние)', 'Pelmeni (srednie)', 275, 10, 12, 28),
  food('f-pelmeni-domashnie', 'Пельмени домашние', 'Pelmeni Domashnie', 290, 11, 14, 28),
  food('f-pelmeni-s-kuritsey', 'Пельмени с курицей', 'Pelmeni S Kuritsey', 230, 12, 8, 25),
  food('f-kotlety-myasnye', 'Котлеты мясные', 'Kotlety Myasnye', 230, 13, 16, 8),
  food('f-kotlety-kurinye', 'Котлеты куриные', 'Kotlety Kurinye', 220, 15, 14, 9),
  food('f-kotlety-domashnie', 'Котлеты домашние', 'Kotlety Domashnie', 250, 14, 18, 7),
  food('f-vareniki-s-tvorogom', 'Вареники с творогом', 'Vareniki S Tvorogom', 220, 8, 6, 30),
  food('f-vareniki-s-kartoshkoy', 'Вареники с картошкой', 'Vareniki S Kartoshkoy', 180, 5, 4, 30),
  food('f-bliny-gotovye', 'Блины готовые', 'Bliny Gotovye', 186, 6, 5, 28),
  food('f-syrniki', 'Сырники', 'Syrniki', 220, 12, 10, 18),
  food('f-hinkali', 'Хинкали', 'Hinkali', 235, 9, 11, 25),
  food('f-manty', 'Манты', 'Manty', 220, 10, 10, 22),
  food('f-tefteli', 'Тефтели', 'Tefteli', 180, 12, 10, 8),
  food('f-frikadelki', 'Фрикадельки', 'Frikadelki', 200, 14, 12, 6),
  food('f-chebureki', 'Чебуреки', 'Chebureki', 280, 9, 16, 25),
  food('f-belyashi', 'Беляши', 'Belyashi', 270, 10, 15, 24),
  food('f-pirozhki-s-myasom', 'Пирожки с мясом', 'Pirozhki S Myasom', 260, 9, 12, 28),
  food('f-naggetsy-zamorozhennye', 'Наггетсы замороженные', 'Naggetsy Zamorozhennye', 250, 14, 14, 15),
  food('f-rybnye-palochki', 'Рыбные палочки', 'Rybnye Palochki', 200, 10, 10, 18),
  food('f-kotlety-rybnye', 'Котлеты рыбные', 'Kotlety Rybnye', 150, 12, 6, 10),
  food('f-kolbasa-varenaya-doktorskaya', 'Колбаса варёная «Докторская»', 'Kolbasa Varenaya «doktorskaya»', 257, 12.8, 22.2, 1.5),
  food('f-kolbasa-varenaya-molochnaya', 'Колбаса варёная «Молочная»', 'Kolbasa Varenaya «molochnaya»', 252, 11.7, 22.8, 0.2),
  food('f-kolbasa-varenaya-lyubitelskaya', 'Колбаса варёная «Любительская»', 'Kolbasa Varenaya «lyubitelskaya»', 301, 12.2, 28, 0.1),
  food('f-kolbasa-varenaya-russkaya', 'Колбаса варёная «Русская»', 'Kolbasa Varenaya «russkaya»', 302, 11.5, 27.9, 1.7),
  food('f-kolbasa-varenaya-chaynaya', 'Колбаса варёная «Чайная»', 'Kolbasa Varenaya «chaynaya»', 216, 11.7, 18.4, 1.9),
  food('f-kolbasa-varenaya-dieticheskaya', 'Колбаса варёная «Диетическая»', 'Kolbasa Varenaya «dieticheskaya»', 170, 12.1, 13.5, 0),
  food('f-kolbasa-varenaya-stolovaya', 'Колбаса варёная «Столовая»', 'Kolbasa Varenaya «stolovaya»', 234, 11.1, 20.2, 1.9),
  food('f-sosiski-molochnye', 'Сосиски молочные', 'Sosiski Molochnye', 260, 11, 23, 1.5),
  food('f-sosiski-russkie', 'Сосиски русские', 'Sosiski Russkie', 220, 12, 19, 0),
  food('f-sosiski-svinye', 'Сосиски свиные', 'Sosiski Svinye', 324, 11.8, 30.8, 0),
  food('f-sardelki-svinye', 'Сардельки свиные', 'Sardelki Svinye', 332, 10.1, 31.6, 1.9),
  food('f-sardelki-govyazhi', 'Сардельки говяжьи', 'Sardelki Govyazhi', 215, 11.4, 18.2, 1.3),
  food('f-servelat', 'Сервелат', 'Servelat', 420, 16, 40, 0),
  food('f-kolbasa-polukopchenaya-krakovskaya', 'Колбаса полукопчёная «Краковская»', 'Kolbasa Polukopchenaya «krakovskaya»', 466, 16.2, 44.6, 0),
  food('f-kolbasa-polukopchenaya-odesskaya', 'Колбаса полукопчёная «Одесская»', 'Kolbasa Polukopchenaya «odesskaya»', 402, 14.8, 38.1, 0.3),
  food('f-kolbasa-vareno-kopchenaya-moskovskaya', 'Колбаса варено-копчёная «Московская»', 'Kolbasa Vareno-kopchenaya «moskovskaya»', 406, 19.1, 36.6, 0.2),
  food('f-kolbasa-syrokopchenaya', 'Колбаса сырокопчёная', 'Kolbasa Syrokopchenaya', 480, 22, 44, 0),
  food('f-vetchina', 'Ветчина', 'Vetchina', 145, 18, 8, 0),
  food('f-bekon', 'Бекон', 'Bekon', 500, 37, 42, 1.4),
  food('f-shpikachki', 'Шпикачки', 'Shpikachki', 337, 10, 33, 0),
  food('f-kolbasa-livernaya', 'Колбаса ливерная', 'Kolbasa Livernaya', 326, 14.4, 28.5, 2.2),
  food('f-kolbasa-kurinaya-varenaya', 'Колбаса куриная варёная', 'Kolbasa Kurinaya Varenaya', 223, 15.5, 16.2, 2.3),
  food('f-karbonad', 'Карбонад', 'Karbonad', 135, 16, 8, 0),
  food('f-grudinka-syrokopchenaya', 'Грудинка сырокопчёная', 'Grudinka Syrokopchenaya', 605, 8.9, 63.3, 0),
  food('f-syvorotochnyy-protein-poroshok', 'Сывороточный протеин (порошок)', 'Whey protein powder', 370, 78, 4, 7),
  food('f-syvorotochnyy-izolyat', 'Сывороточный изолят', 'Syvorotochnyy Izolyat', 360, 88, 1, 2),
  food('f-kazeinovyy-protein', 'Казеиновый протеин', 'Kazeinovyy Protein', 360, 80, 2, 6),
  food('f-soevyy-protein', 'Соевый протеин', 'Soevyy Protein', 350, 80, 2, 5),
  food('f-gorohovyy-protein', 'Гороховый протеин', 'Gorohovyy Protein', 370, 80, 5, 4),
  food('f-proteinovyy-kokteyl-gotovyy', 'Протеиновый коктейль (готовый)', 'Proteinovyy Kokteyl (gotovyy)', 80, 15, 1.5, 3),
  food('f-proteinovyy-batonchik', 'Протеиновый батончик', 'Proteinovyy Batonchik', 360, 25, 12, 30),
  food('f-geyner-poroshok', 'Гейнер (порошок)', 'Geyner (poroshok)', 380, 25, 5, 60),
  food('f-aminokisloty-bcaa-poroshok', 'Аминокислоты BCAA (порошок)', 'Aminokisloty Bcaa (poroshok)', 350, 80, 0, 5),
  food('f-protein-na-vode-portsiya-30-g', 'Протеин на воде (порция 30 г)', 'Protein Na Vode (portsiya 30 G)', 110, 24, 1, 2),
  food('f-kofe-chernyy-bez-sahara', 'Кофе чёрный (без сахара)', 'Black coffee (no sugar)', 2, 0.2, 0, 0.3),
  food('f-amerikano', 'Американо', 'Amerikano', 5, 0.3, 0.1, 0.5),
  food('f-espresso', 'Эспрессо', 'Espresso', 9, 0.5, 0.2, 0.8),
  food('f-kapuchino-na-moloke-3-2', 'Капучино (на молоке 3.2%)', 'Kapuchino (na Moloke 3.2%)', 50, 2.5, 2.8, 4),
  food('f-latte', 'Латте', 'Latte', 45, 2.5, 2.5, 4),
  food('f-flet-uayt', 'Флэт уайт', 'Flet Uayt', 55, 3, 3, 4.5),
  food('f-mokko', 'Мокко', 'Mokko', 90, 3, 3.5, 12),
  food('f-glyase', 'Глясе', 'Glyase', 120, 3.5, 4, 18),
  food('f-kofe-s-molokom', 'Кофе с молоком', 'Kofe S Molokom', 58, 1.5, 1.5, 8),
  food('f-kofe-3v1-rastvorimyy', 'Кофе 3в1 (растворимый)', 'Kofe 3v1 (rastvorimyy)', 430, 2, 12, 75),
  food('f-rastvorimyy-kofe-poroshok', 'Растворимый кофе (порошок)', 'Rastvorimyy Kofe (poroshok)', 100, 15, 0.5, 10),
  food('f-kakao-na-moloke', 'Какао на молоке', 'Kakao Na Moloke', 80, 3.5, 3, 10),
  food('f-mors-klyukvennyy', 'Морс клюквенный', 'Mors Klyukvennyy', 45, 0.1, 0, 11.5),
  food('f-mors-brusnichnyy', 'Морс брусничный', 'Mors Brusnichnyy', 41, 0.1, 0, 10.9),
  food('f-mors-smorodinovyy', 'Морс смородиновый', 'Mors Smorodinovyy', 40, 0.2, 0, 10),
  food('f-mors-malinovyy', 'Морс малиновый', 'Mors Malinovyy', 42, 0.2, 0, 10.5),
  food('f-mors-chernichnyy', 'Морс черничный', 'Mors Chernichnyy', 43, 0.2, 0, 11),
  food('f-mors-oblepihovyy', 'Морс облепиховый', 'Mors Oblepihovyy', 50, 0.3, 0.5, 11.5),
  food('f-mors-iz-shipovnika', 'Морс из шиповника', 'Mors Iz Shipovnika', 35, 0.5, 0, 8),
  food('f-yaytso-kurinoe-otvarnoe-vkrutuyu', 'Яйцо куриное отварное (вкрутую)', 'Hard-boiled egg', 155, 12.6, 10.6, 1.1),
  food('f-yaytso-kurinoe-varenoe-vsmyatku', 'Яйцо куриное варёное всмятку', 'Yaytso Kurinoe Varenoe Vsmyatku', 159, 12.8, 11.6, 0.8),
  food('f-yaytso-kurinoe-syroe', 'Яйцо куриное сырое', 'Yaytso Kurinoe Syroe', 157, 12.7, 10.9, 0.7),
  food('f-belok-yaytsa-varenyy', 'Белок яйца варёный', 'Belok Yaytsa Varenyy', 52, 11, 0.2, 0.7),
  food('f-zheltok-yaytsa-varenyy', 'Желток яйца варёный', 'Zheltok Yaytsa Varenyy', 322, 16, 27, 3.6),
  food('f-omlet-naturalnyy', 'Омлет натуральный', 'Omlet Naturalnyy', 184, 9.6, 15.4, 1.9),
  food('f-yaichnitsa-glazunya', 'Яичница глазунья', 'Yaichnitsa Glazunya', 196, 13.6, 15.3, 0.9),
  food('f-yaytso-perepelinoe-varenoe', 'Яйцо перепелиное варёное', 'Yaytso Perepelinoe Varenoe', 168, 11.9, 13.1, 0.6),
  food('f-borsch-ukrainskiy', 'Борщ украинский', 'Borsch Ukrainskiy', 49, 1.1, 2.2, 6.7),
  food('f-borsch-moskovskiy', 'Борщ московский', 'Borsch Moskovskiy', 80, 5, 4.5, 5),
  food('f-borsch-s-myasom', 'Борщ с мясом', 'Borsch S Myasom', 65, 4, 3.5, 5.5),
  food('f-borsch-vegetarianskiy', 'Борщ вегетарианский', 'Borsch Vegetarianskiy', 35, 0.5, 2.7, 2.2),
  food('f-schi-iz-svezhey-kapusty', 'Щи из свежей капусты', 'Schi Iz Svezhey Kapusty', 33, 1, 1.9, 3.4),
  food('f-schi-iz-kvashenoy-kapusty', 'Щи из квашеной капусты', 'Schi Iz Kvashenoy Kapusty', 37, 2, 2.8, 1),
  food('f-schi-zelenye-s-yaytsom', 'Щи зелёные с яйцом', 'Schi Zelenye S Yaytsom', 45, 1.9, 3.2, 2.2),
  food('f-solyanka-sbornaya-myasnaya', 'Солянка сборная мясная', 'Solyanka Sbornaya Myasnaya', 69, 5.2, 4.6, 1.7),
  food('f-solyanka-rybnaya', 'Солянка рыбная', 'Solyanka Rybnaya', 25, 2.4, 1.2, 1.2),
  food('f-rassolnik', 'Рассольник', 'Rassolnik', 54, 1.6, 2, 7),
  food('f-rassolnik-leningradskiy', 'Рассольник ленинградский', 'Rassolnik Leningradskiy', 53, 1.3, 1.7, 8.8),
  food('f-uha', 'Уха', 'Uha', 46, 4.5, 2, 2),
  food('f-uha-rybatskaya', 'Уха рыбацкая', 'Uha Rybatskaya', 67, 8.5, 1.9, 4.3),
  food('f-sup-kurinyy', 'Суп куриный', 'Sup Kurinyy', 50, 2.5, 2, 5.5),
  food('f-sup-kurinyy-s-makaronami', 'Суп куриный с макаронами', 'Sup Kurinyy S Makaronami', 60, 4.5, 3.3, 3.1),
  food('f-sup-gorohovyy', 'Суп гороховый', 'Sup Gorohovyy', 54, 2.2, 3, 5),
  food('f-sup-gribnoy', 'Суп грибной', 'Sup Gribnoy', 51, 0.8, 3.4, 4.6),
  food('f-sup-kartofelnyy', 'Суп картофельный', 'Sup Kartofelnyy', 51, 1.3, 1.1, 9.4),
  food('f-sup-ovoschnoy', 'Суп овощной', 'Sup Ovoschnoy', 37, 1.7, 1.6, 4.2),
  food('f-sup-pyure-ovoschnoy', 'Суп-пюре овощной', 'Sup-pyure Ovoschnoy', 55, 1.8, 3.2, 5),
  food('f-harcho', 'Харчо', 'Harcho', 115, 8, 3.6, 13.6),
  food('f-okroshka-na-kvase', 'Окрошка на квасе', 'Okroshka Na Kvase', 56, 2.9, 2.6, 5.8),
  food('f-okroshka-myasnaya', 'Окрошка мясная', 'Okroshka Myasnaya', 70, 4, 3.5, 6),
  food('f-svekolnik', 'Свекольник', 'Svekolnik', 36, 0.5, 2, 4.2),
  food('f-bulon-kurinyy', 'Бульон куриный', 'Bulon Kurinyy', 15, 2, 0.5, 0.3),
  food('f-bulon-govyazhiy', 'Бульон говяжий', 'Bulon Govyazhiy', 10, 1.5, 0.3, 0),
  food('f-sup-fasolevyy', 'Суп фасолевый', 'Sup Fasolevyy', 48, 2.3, 1.6, 6.6),
  food('f-sup-s-frikadelkami', 'Суп с фрикадельками', 'Sup S Frikadelkami', 70, 4.5, 3.5, 5),
  food('f-sup-molochnyy-s-risom', 'Суп молочный с рисом', 'Sup Molochnyy S Risom', 62, 2.2, 2.8, 7.5),
  food('f-sup-lapsha', 'Суп-лапша', 'Sup-lapsha', 48, 1.2, 2.4, 5.9),
  food('f-sup-syrnyy', 'Суп сырный', 'Sup Syrnyy', 93, 4.7, 6.9, 3.2),
  food('f-sup-tomatnyy', 'Суп томатный', 'Sup Tomatnyy', 28, 1.3, 1.8, 1.9),
  food('f-sup-iz-tsvetnoy-kapusty', 'Суп из цветной капусты', 'Sup Iz Tsvetnoy Kapusty', 37, 1, 3.2, 1.1),
  food('f-sup-chechevichnyy', 'Суп чечевичный', 'Sup Chechevichnyy', 68, 2.5, 4.2, 5.2),
  food('f-minestrone', 'Минестроне', 'Minestrone', 45, 2, 1.5, 6),
  food('f-gaspacho', 'Гаспачо', 'Gaspacho', 30, 1, 1, 4.5),
  food('f-krem-sup-tykvennyy', 'Крем-суп тыквенный', 'Krem-sup Tykvennyy', 49, 1.2, 2.5, 4.8),
  food('f-sup-s-pelmenyami', 'Суп с пельменями', 'Sup S Pelmenyami', 80, 5, 3.5, 8),
  food('f-kotleta-myasnaya-zharenaya', 'Котлета мясная жареная', 'Kotleta Myasnaya Zharenaya', 250, 14, 18, 9),
  food('f-kotleta-kurinaya', 'Котлета куриная', 'Kotleta Kurinaya', 220, 15, 14, 9),
  food('f-kotleta-parovaya', 'Котлета паровая', 'Kotleta Parovaya', 195, 16, 12, 6),
  food('f-kotleta-po-kievski', 'Котлета по-киевски', 'Kotleta Po-kievski', 290, 15, 20, 12),
  food('f-gulyash-iz-govyadiny', 'Гуляш из говядины', 'Gulyash Iz Govyadiny', 160, 15, 9, 5),
  food('f-gulyash-iz-svininy', 'Гуляш из свинины', 'Gulyash Iz Svininy', 230, 14, 17, 3),
  food('f-befstroganov', 'Бефстроганов', 'Befstroganov', 200, 15, 12, 6),
  food('f-azu', 'Азу', 'Azu', 178, 9.3, 12.3, 7.3),
  food('f-plov-s-kuritsey', 'Плов с курицей', 'Plov S Kuritsey', 205, 10, 8, 22),
  food('f-plov-s-govyadinoy', 'Плов с говядиной', 'Plov S Govyadinoy', 219, 13, 9, 19),
  food('f-plov-so-svininoy', 'Плов со свининой', 'Plov So Svininoy', 265, 13, 13, 17),
  food('f-golubtsy', 'Голубцы', 'Golubtsy', 180, 8, 10, 12),
  food('f-perets-farshirovannyy', 'Перец фаршированный', 'Perets Farshirovannyy', 160, 7, 9, 12),
  food('f-pechen-tushenaya', 'Печень тушёная', 'Pechen Tushenaya', 150, 16, 7, 5),
  food('f-pechen-po-stroganovski', 'Печень по-строгановски', 'Pechen Po-stroganovski', 180, 14, 10, 6),
  food('f-ryba-zharenaya', 'Рыба жареная', 'Ryba Zharenaya', 180, 18, 11, 3),
  food('f-ryba-zapechennaya', 'Рыба запечённая', 'Ryba Zapechennaya', 130, 18.5, 5.5, 1),
  food('f-ryba-otvarnaya', 'Рыба отварная', 'Ryba Otvarnaya', 90, 18, 1.5, 0),
  food('f-kuritsa-otvarnaya', 'Курица отварная', 'Kuritsa Otvarnaya', 170, 25, 7, 0),
  food('f-kuritsa-zharenaya', 'Курица жареная', 'Kuritsa Zharenaya', 210, 18, 14, 0),
  food('f-kuritsa-zapechennaya', 'Курица запечённая', 'Kuritsa Zapechennaya', 180, 20, 10, 0),
  food('f-shashlyk-iz-svininy', 'Шашлык из свинины', 'Shashlyk Iz Svininy', 280, 20, 22, 0),
  food('f-shashlyk-iz-kuritsy', 'Шашлык из курицы', 'Shashlyk Iz Kuritsy', 180, 22, 10, 0),
  food('f-lyulya-kebab', 'Люля-кебаб', 'Lyulya-kebab', 250, 18, 18, 5),
  food('f-antrekot', 'Антрекот', 'Antrekot', 280, 22, 20, 0),
  food('f-bifshteks', 'Бифштекс', 'Bifshteks', 250, 20, 18, 0),
  food('f-otbivnaya-svinaya', 'Отбивная свиная', 'Otbivnaya Svinaya', 250, 19, 16, 1),
  food('f-otbivnaya-kurinaya', 'Отбивная куриная', 'Otbivnaya Kurinaya', 190, 18, 9, 5),
  food('f-makarony-po-flotski', 'Макароны по-флотски', 'Makarony Po-flotski', 220, 10, 10, 22),
  food('f-zharkoe', 'Жаркое', 'Zharkoe', 200, 12, 12, 10),
  food('f-ragu-ovoschnoe-s-myasom', 'Рагу овощное с мясом', 'Ragu Ovoschnoe S Myasom', 140, 8, 7, 10),
  food('f-kapusta-tushenaya-s-myasom', 'Капуста тушёная с мясом', 'Kapusta Tushenaya S Myasom', 120, 8, 6, 8),
  food('f-kartofel-tushenyy-s-myasom', 'Картофель тушёный с мясом', 'Kartofel Tushenyy S Myasom', 160, 10, 8, 12),
  food('f-bliny-s-myasom', 'Блины с мясом', 'Bliny S Myasom', 220, 10, 10, 22),
  food('f-pelmeni-varenye', 'Пельмени варёные', 'Pelmeni Varenye', 250, 12, 10, 28),
  food('f-lazanya', 'Лазанья', 'Lazanya', 180, 9, 8, 18),
  food('f-pasta-boloneze', 'Паста болоньезе', 'Pasta Boloneze', 160, 8, 6, 18),
  food('f-rizotto', 'Ризотто', 'Rizotto', 150, 5, 5, 22),
  food('f-omlet-s-syrom', 'Омлет с сыром', 'Omlet S Syrom', 200, 12, 15, 2),
  food('f-yaichnitsa-s-bekonom', 'Яичница с беконом', 'Yaichnitsa S Bekonom', 250, 14, 20, 1),
  food('f-holodets', 'Холодец', 'Holodets', 180, 20, 10, 2),
  food('f-zalivnoe-rybnoe', 'Заливное рыбное', 'Zalivnoe Rybnoe', 80, 12, 2, 2),
  food('f-kartofelnoe-pyure', 'Картофельное пюре', 'Kartofelnoe Pyure', 106, 2.1, 3.3, 16),
  food('f-kartofel-otvarnoy', 'Картофель отварной', 'Kartofel Otvarnoy', 82, 2, 0.4, 16.7),
  food('f-kartofel-zharenyy', 'Картофель жареный', 'Kartofel Zharenyy', 192, 2.8, 9.5, 23),
  food('f-kartofel-zapechennyy', 'Картофель запечённый', 'Kartofel Zapechennyy', 93, 2.5, 0.1, 21),
  food('f-kartofel-fri-domashniy', 'Картофель фри (домашний)', 'Kartofel Fri (domashniy)', 250, 3, 12, 32),
  food('f-grechka-varenaya-s-maslom', 'Гречка варёная с маслом', 'Grechka Varenaya S Maslom', 130, 4.5, 3, 21),
  food('f-ris-otvarnoy-s-maslom', 'Рис отварной с маслом', 'Ris Otvarnoy S Maslom', 150, 2.5, 3, 28),
  food('f-makarony-otvarnye-s-maslom', 'Макароны отварные с маслом', 'Makarony Otvarnye S Maslom', 140, 4, 3, 24),
  food('f-kasha-ovsyanaya-na-moloke', 'Каша овсяная на молоке', 'Kasha Ovsyanaya Na Moloke', 102, 3.2, 4.1, 14.2),
  food('f-kasha-risovaya-na-moloke', 'Каша рисовая на молоке', 'Kasha Risovaya Na Moloke', 97, 2.5, 3, 16),
  food('f-kasha-mannaya-na-moloke', 'Каша манная на молоке', 'Kasha Mannaya Na Moloke', 98, 3, 3.2, 15.3),
  food('f-kasha-pshennaya', 'Каша пшённая', 'Kasha Pshennaya', 90, 3, 0.7, 17),
  food('f-kasha-perlovaya', 'Каша перловая', 'Kasha Perlovaya', 109, 3.1, 0.4, 23),
  food('f-ovoschnoe-ragu', 'Овощное рагу', 'Ovoschnoe Ragu', 80, 2, 4, 9),
  food('f-kapusta-tushenaya', 'Капуста тушёная', 'Kapusta Tushenaya', 75, 2, 4, 7),
  food('f-kabachki-tushenye', 'Кабачки тушёные', 'Kabachki Tushenye', 50, 1, 3, 5),
  food('f-svekla-tushenaya', 'Свёкла тушёная', 'Svekla Tushenaya', 60, 1.5, 2, 9),
  food('f-morkov-tushenaya', 'Морковь тушёная', 'Morkov Tushenaya', 55, 1, 2, 8),
  food('f-fasol-tushenaya', 'Фасоль тушёная', 'Fasol Tushenaya', 90, 5, 2, 12),
  food('f-goroshek-zelenyy-s-maslom', 'Горошек зелёный с маслом', 'Goroshek Zelenyy S Maslom', 80, 5, 3, 10),
  food('f-kukuruza-varenaya', 'Кукуруза варёная', 'Kukuruza Varenaya', 90, 3, 1, 19),
  food('f-salat-ovoschnoy-vinegret', 'Салат овощной (винегрет)', 'Salat Ovoschnoy (vinegret)', 130, 2, 8, 12),
  food('f-salat-olive', 'Салат оливье', 'Salat Olive', 180, 5, 14, 8),
  food('f-salat-grecheskiy', 'Салат греческий', 'Salat Grecheskiy', 96, 2.5, 7.5, 4.5),
  food('f-salat-tsezar-bez-kuritsy', 'Салат цезарь (без курицы)', 'Salat Tsezar (bez Kuritsy)', 150, 4, 12, 6),
  food('f-salat-iz-svezhih-ovoschey', 'Салат из свежих овощей', 'Salat Iz Svezhih Ovoschey', 40, 1.5, 2, 4),
  food('f-kapusta-kvashenaya', 'Капуста квашеная', 'Kapusta Kvashenaya', 20, 1.5, 0.1, 3),
  food('f-ogurtsy-solenye', 'Огурцы солёные', 'Ogurtsy Solenye', 15, 1, 0.1, 2),
  food('f-pomidory-solenye', 'Помидоры солёные', 'Pomidory Solenye', 20, 1, 0.2, 3),
  food('f-ikra-kabachkovaya', 'Икра кабачковая', 'Ikra Kabachkovaya', 100, 1.5, 7, 8),
  food('f-ikra-baklazhannaya', 'Икра баклажанная', 'Ikra Baklazhannaya', 120, 1.5, 9, 8),
  food('f-lecho', 'Лечо', 'Lecho', 60, 1.5, 3, 7),
  food('f-ratatuy', 'Рататуй', 'Ratatuy', 70, 1.5, 4, 7),
  food('f-pyure-iz-goroha', 'Пюре из гороха', 'Pyure Iz Goroha', 100, 6, 2, 14),
  food('f-pyure-iz-morkovi', 'Пюре из моркови', 'Pyure Iz Morkovi', 50, 1, 1, 9),
  food('f-pyure-iz-tykvy', 'Пюре из тыквы', 'Pyure Iz Tykvy', 45, 1, 1, 8),
  food('f-brokkoli-na-paru', 'Брокколи на пару', 'Brokkoli Na Paru', 35, 3, 0.4, 7),
  food('f-sparzha-na-paru', 'Спаржа на пару', 'Sparzha Na Paru', 25, 2.5, 0.2, 4),
  food('f-tsvetnaya-kapusta-na-paru', 'Цветная капуста на пару', 'Tsvetnaya Kapusta Na Paru', 30, 2.5, 0.3, 5),
  food('f-kuskus-varenyy', 'Кускус варёный', 'Kuskus Varenyy', 112, 3.8, 0.2, 23),
  food('f-bulgur-s-ovoschami', 'Булгур с овощами', 'Bulgur S Ovoschami', 100, 3.5, 1, 20),
  food('f-kinoa-s-ovoschami', 'Киноа с овощами', 'Kinoa S Ovoschami', 120, 4.5, 2, 20),
  food('f-lapsha-grechnevaya-soba', 'Лапша гречневая (соба)', 'Lapsha Grechnevaya (soba)', 100, 5, 1, 20),
  food('f-kartofelnye-zrazy', 'Картофельные зразы', 'Kartofelnye Zrazy', 180, 4, 8, 22),
  food('f-draniki', 'Драники', 'Draniki', 150, 3, 6, 20),
  food('f-olive-klassicheskiy', 'Оливье классический', 'Olive Klassicheskiy', 180, 5.5, 14, 8),
  food('f-olive-s-kuritsey', 'Оливье с курицей', 'Olive S Kuritsey', 170, 7, 12, 7),
  food('f-vinegret', 'Винегрет', 'Vinegret', 130, 1.7, 10, 8.2),
  food('f-vinegret-s-gribami', 'Винегрет с грибами', 'Vinegret S Gribami', 120, 2.5, 8, 9),
  food('f-seledka-pod-shuboy', 'Селёдка под шубой', 'Seledka Pod Shuboy', 183, 6, 14.5, 7),
  food('f-krabovyy-salat', 'Крабовый салат', 'Krabovyy Salat', 160, 6, 10, 10),
  food('f-grecheskiy-salat', 'Греческий салат', 'Grecheskiy Salat', 100, 3, 8, 4),
  food('f-tsezar-s-kuritsey', 'Цезарь с курицей', 'Tsezar S Kuritsey', 190, 12, 14, 6),
  food('f-tsezar-klassicheskiy', 'Цезарь классический', 'Tsezar Klassicheskiy', 170, 8, 13, 5),
  food('f-tsezar-s-krevetkami', 'Цезарь с креветками', 'Tsezar S Krevetkami', 160, 10, 11, 5),
  food('f-salat-ovoschnoy-s-maslom', 'Салат овощной с маслом', 'Salat Ovoschnoy S Maslom', 70, 1.5, 5, 5),
  food('f-kapustnyy-salat', 'Капустный салат', 'Kapustnyy Salat', 50, 1.5, 3, 4),
  food('f-morkovnyy-salat', 'Морковный салат', 'Morkovnyy Salat', 60, 1, 3, 7),
  food('f-svekolnyy-salat', 'Свекольный салат', 'Svekolnyy Salat', 70, 1.5, 3, 9),
  food('f-salat-iz-ogurtsov-i-pomidorov', 'Салат из огурцов и помидоров', 'Salat Iz Ogurtsov I Pomidorov', 35, 1, 2, 4),
  food('f-mimoza', 'Мимоза', 'Mimoza', 200, 6, 16, 6),
  food('f-stolichnyy', 'Столичный', 'Stolichnyy', 220, 10, 18, 5),
  food('f-salat-s-tuntsom', 'Салат с тунцом', 'Salat S Tuntsom', 120, 10, 6, 5),
  food('f-salat-s-krevetkami', 'Салат с креветками', 'Salat S Krevetkami', 90, 8, 4, 5),
  food('f-salat-s-kuritsey-i-ananasom', 'Салат с курицей и ананасом', 'Salat S Kuritsey I Ananasom', 150, 10, 8, 10),
  food('f-salat-s-gribami', 'Салат с грибами', 'Salat S Gribami', 110, 4, 8, 5),
  food('f-salat-s-syrom-feta', 'Салат с сыром фета', 'Salat S Syrom Feta', 140, 5, 12, 3),
  food('f-salat-kapreze', 'Салат Капрезе', 'Salat Kapreze', 150, 8, 12, 3),
  food('f-salat-s-avokado', 'Салат с авокадо', 'Salat S Avokado', 160, 3, 14, 5),
  food('f-salat-nisuaz', 'Салат Нисуаз', 'Salat Nisuaz', 140, 12, 8, 4),
  food('f-salat-s-kalmarami', 'Салат с кальмарами', 'Salat S Kalmarami', 100, 12, 4, 3),
  food('f-salat-s-yazykom', 'Салат с языком', 'Salat S Yazykom', 180, 12, 14, 3),
  food('f-salat-pechenochnyy', 'Салат печёночный', 'Salat Pechenochnyy', 160, 8, 12, 5),
  food('f-salat-s-krabovymi-palochkami', 'Салат с крабовыми палочками', 'Salat S Krabovymi Palochkami', 140, 5, 9, 9),
  food('f-salat-iz-kapusty-s-morkovyu', 'Салат из капусты с морковью', 'Salat Iz Kapusty S Morkovyu', 45, 1.5, 2, 6),
  food('f-salat-vitaminnyy', 'Салат витаминный', 'Salat Vitaminnyy', 50, 1.5, 2, 7),
  food('f-salat-iz-svekly-s-chesnokom', 'Салат из свёклы с чесноком', 'Salat Iz Svekly S Chesnokom', 80, 2, 5, 7),
  food('f-salat-iz-redisa', 'Салат из редиса', 'Salat Iz Redisa', 30, 1, 1, 4),
  food('f-salat-iz-rukkoly', 'Салат из рукколы', 'Salat Iz Rukkoly', 50, 2, 3, 3),
  food('f-salat-s-yaytsom-i-zelenym-goroshkom', 'Салат с яйцом и зелёным горошком', 'Salat S Yaytsom I Zelenym Goroshkom', 120, 6, 8, 6),
  food('f-salat-s-vetchinoy-i-syrom', 'Салат с ветчиной и сыром', 'Salat S Vetchinoy I Syrom', 200, 12, 15, 4),
  food('f-salat-s-kopchenoy-kuritsey', 'Салат с копчёной курицей', 'Salat S Kopchenoy Kuritsey', 180, 14, 12, 5),
  food('f-salat-iz-morskoy-kapusty', 'Салат из морской капусты', 'Salat Iz Morskoy Kapusty', 60, 1.5, 3, 6),
  food('f-salat-s-fasolyu', 'Салат с фасолью', 'Salat S Fasolyu', 100, 5, 5, 8),
  food('f-morozhenoe-plombir', 'Мороженое пломбир', 'Plombir ice cream', 230, 3.5, 15, 20),
  food('f-morozhenoe-vanilnoe', 'Мороженое ванильное', 'Morozhenoe Vanilnoe', 210, 3.5, 11, 23),
  food('f-morozhenoe-shokoladnoe', 'Мороженое шоколадное', 'Morozhenoe Shokoladnoe', 250, 4, 14, 28),
  food('f-morozhenoe-fruktovoe', 'Мороженое фруктовое', 'Morozhenoe Fruktovoe', 150, 2, 3, 30),
  food('f-syrniki-so-smetanoy', 'Сырники со сметаной', 'Syrniki So Smetanoy', 250, 11, 14, 20),
  food('f-bliny-so-smetanoy', 'Блины со сметаной', 'Bliny So Smetanoy', 220, 6, 10, 28),
  food('f-bliny-s-tvorogom', 'Блины с творогом', 'Bliny S Tvorogom', 230, 8, 8, 30),
  food('f-sharlotka', 'Шарлотка', 'Sharlotka', 200, 4, 6, 35),
  food('f-yablochnyy-pirog', 'Яблочный пирог', 'Yablochnyy Pirog', 250, 4, 10, 38),
  food('f-medovik', 'Медовик', 'Medovik', 350, 5, 15, 50),
  food('f-napoleon', 'Наполеон', 'Napoleon', 380, 5, 20, 45),
  food('f-praga', 'Прага', 'Praga', 350, 5, 18, 40),
  food('f-tiramisu', 'Тирамису', 'Tiramisu', 280, 5, 15, 30),
  food('f-chizkeyk', 'Чизкейк', 'Chizkeyk', 320, 6, 20, 28),
  food('f-ekler', 'Эклер', 'Ekler', 330, 5, 20, 32),
  food('f-profitroli', 'Профитроли', 'Profitroli', 300, 6, 18, 28),
  food('f-beze', 'Безе', 'Beze', 300, 2.5, 0, 75),
  food('f-zefir', 'Зефир', 'Zefir', 300, 0.8, 0.1, 78),
  food('f-pastila', 'Пастила', 'Pastila', 320, 0.5, 0, 80),
  food('f-marmelad', 'Мармелад', 'Marmelad', 300, 0.5, 0, 75),
  food('f-zhele-fruktovoe', 'Желе фруктовое', 'Zhele Fruktovoe', 70, 2.5, 0, 16),
  food('f-puding-risovyy', 'Пудинг рисовый', 'Puding Risovyy', 130, 3, 3, 22),
  food('f-puding-shokoladnyy', 'Пудинг шоколадный', 'Puding Shokoladnyy', 150, 3.5, 5, 24),
  food('f-sufle', 'Суфле', 'Sufle', 200, 5, 10, 20),
  food('f-tvorozhnaya-zapekanka', 'Творожная запеканка', 'Tvorozhnaya Zapekanka', 180, 12, 6, 18),
  food('f-vareniki-s-vishney', 'Вареники с вишней', 'Vareniki S Vishney', 200, 5, 4, 35),
  food('f-vareniki-s-tvorogom-sladkie', 'Вареники с творогом сладкие', 'Vareniki S Tvorogom Sladkie', 210, 8, 5, 32),
  food('f-pirozhnoe-kartoshka', 'Пирожное картошка', 'Pirozhnoe Kartoshka', 350, 5, 20, 35),
  food('f-pirozhnoe-korzinochka', 'Пирожное корзиночка', 'Pirozhnoe Korzinochka', 350, 4, 18, 42),
  food('f-vafli', 'Вафли', 'Vafli', 450, 5, 25, 50),
  food('f-pechene-pesochnoe', 'Печенье песочное', 'Pechene Pesochnoe', 450, 6, 20, 60),
  food('f-pryaniki', 'Пряники', 'Pryaniki', 350, 5, 5, 70),
  food('f-shokolad-molochnyy', 'Шоколад молочный', 'Shokolad Molochnyy', 540, 7, 30, 55),
  food('f-shokolad-temnyy', 'Шоколад тёмный', 'Shokolad Temnyy', 550, 5, 35, 50),
  food('f-konfety-shokoladnye', 'Конфеты шоколадные', 'Konfety Shokoladnye', 500, 5, 25, 60),
  food('f-halva', 'Халва', 'Halva', 500, 12, 30, 50),
  food('f-kozinak', 'Козинак', 'Kozinak', 480, 12, 28, 50),
  food('f-med', 'Мед', 'Med', 328, 0.8, 0, 80),
  food('f-varene', 'Варенье', 'Varene', 250, 0.3, 0, 65),
  food('f-dzhem', 'Джем', 'Dzhem', 250, 0.4, 0, 65),
  food('f-molochnyy-kokteyl', 'Молочный коктейль', 'Molochnyy Kokteyl', 120, 3.5, 4, 18),
  food('f-tiramisu-legkiy', 'Тирамису лёгкий', 'Tiramisu Legkiy', 200, 6, 8, 25),
  food('f-fruktovyy-salat', 'Фруктовый салат', 'Fruktovyy Salat', 50, 0.5, 0.2, 12),
  food('f-kompot-iz-svezhih-fruktov', 'Компот из свежих фруктов', 'Kompot Iz Svezhih Fruktov', 50, 0.3, 0, 12),
  food('f-kisel', 'Кисель', 'Kisel', 55, 0.2, 0, 13),
  food('f-muss-tvorozhnyy', 'Мусс творожный', 'Muss Tvorozhnyy', 150, 8, 5, 18),
  food('f-parfe', 'Парфе', 'Parfe', 180, 4, 10, 18),
]

export const SEED_EXERCISES: Exercise[] = [
  // Chest
  ex('e-bench-press', 'Жим штанги лёжа', 'Barbell Bench Press', 'chest', ['triceps', 'shoulders'], 'barbell',
    'Лёжа на скамье, штанга на уровне груди. Опустите к середине груди, выжмите вверх. Лопатки сведены, стопы на полу.'),
  ex('e-incline-bench', 'Жим штанги наклон', 'Incline Barbell Bench', 'chest', ['shoulders', 'triceps'], 'barbell',
    'Скамья 30–45°. Опустите штангу к верхней части груди, выжмите вверх. Не отрывайте поясницу.'),
  ex('e-decline-bench', 'Жим штанги вниз', 'Decline Bench Press', 'chest', ['triceps'], 'barbell',
    'Скамья с отрицательным наклоном. Опустите штангу к нижней части груди, выжмите вверх под контролем.'),
  ex('e-db-bench', 'Жим гантелей лёжа', 'Dumbbell Bench Press', 'chest', ['triceps', 'shoulders'], 'dumbbell',
    'Лёжа, гантели над грудью. Опустите до уровня груди, локти ~45°, выжмите и слегка сведите вверху.'),
  ex('e-db-incline', 'Жим гантелей наклон', 'Incline DB Press', 'chest', ['shoulders', 'triceps'], 'dumbbell',
    'Наклон 30–45°, гантели над верхней грудью. Опустите с контролем, выжмите вверх.'),
  ex('e-db-fly', 'Разведение гантелей', 'Dumbbell Fly', 'chest', [], 'dumbbell',
    'Лёжа, гантели над грудью, мягкие локти. Разведите руки в стороны по дуге, сведите обратно.'),
  ex('e-cable-fly', 'Сведение в кроссовере', 'Cable Fly', 'chest', [], 'cable',
    'Стоя между блоками, сведите рукояти перед грудью по дуге. Лёгкий наклон вперёд, локти слегка согнуты.'),
  ex('e-pec-deck', 'Бабочка', 'Pec Deck', 'chest', [], 'machine',
    'Сядьте в тренажёр, предплечья на подушках. Сведите руки перед собой, медленно разведите.'),
  ex('e-push-up', 'Отжимания', 'Push-up', 'chest', ['triceps', 'shoulders'], 'bodyweight',
    'Упор лёжа, тело в линию. Опуститесь грудью к полу, выжмите вверх. Не провисайте в пояснице.'),
  ex('e-dips-chest', 'Брусья (грудь)', 'Chest Dips', 'chest', ['triceps', 'shoulders'], 'bodyweight',
    'На брусьях корпус слегка наклонён вперёд. Опуститесь, сгибая локти, поднимитесь. Работа на грудь.'),
  ex('e-machine-chest', 'Жим в тренажёре', 'Machine Chest Press', 'chest', ['triceps'], 'machine',
    'Сядьте, рукояти на уровне груди. Выжмите вперёд до почти прямых рук, верните с контролем.'),
  ex('e-landmine-press', 'Жим лэндмайн', 'Landmine Press', 'chest', ['shoulders'], 'barbell',
    'Один конец грифа в упоре. Выжимайте гриф вверх-вперёд от плеча, корпус стабилен.'),
  // Back
  ex('e-deadlift', 'Становая тяга', 'Conventional Deadlift', 'back', ['hamstrings', 'glutes', 'traps'], 'barbell',
    'Ноги на ширине таза, хват за гриф. Встаньте, разгибая бёдра и колени, штанга близко к телу. Опустите обратно.'),
  ex('e-sumo-dl', 'Становая сумо', 'Sumo Deadlift', 'back', ['glutes', 'quads'], 'barbell',
    'Широкая стойка, носки наружу. Тяните штангу вверх, держа спину прямой, таз подключайте активно.'),
  ex('e-rdl', 'Румынская тяга', 'Romanian Deadlift', 'hamstrings', ['glutes', 'back'], 'barbell',
    'Слегка согнутые колени, наклон от бёдер. Опустите штангу вдоль ног, почувствуйте заднюю поверхность, встаньте.'),
  ex('e-pull-up', 'Подтягивания', 'Pull-up', 'back', ['biceps'], 'bodyweight',
    'Вис прямым хватом. Подтянитесь подбородком выше перекладины, опуститесь до почти прямых рук.'),
  ex('e-chin-up', 'Подтягивания обр. хват', 'Chin-up', 'back', ['biceps'], 'bodyweight',
    'Вис обратным хватом. Подтянитесь, локти вниз, опуститесь под контролем. Больше бицепса.'),
  ex('e-lat-pulldown', 'Тяга верхнего блока', 'Lat Pulldown', 'back', ['biceps'], 'cable',
    'Сядьте, тяните гриф к верхней груди. Сводите лопатки, не отклоняйтесь сильно назад.'),
  ex('e-barbell-row', 'Тяга штанги в наклоне', 'Barbell Row', 'back', ['biceps'], 'barbell',
    'Наклон от бёдер, тяните штангу к поясу. Локти вдоль корпуса, спина нейтральна.'),
  ex('e-db-row', 'Тяга гантели', 'One-Arm DB Row', 'back', ['biceps'], 'dumbbell',
    'Упор одной рукой, тяните гантель к поясу. Лопатку к позвоночнику, без вращения корпуса.'),
  ex('e-seated-row', 'Тяга горизонтальная', 'Seated Cable Row', 'back', ['biceps'], 'cable',
    'Сидя, тяните рукоять к животу. Грудь вперёд, сведите лопатки, плавно выпрямите руки.'),
  ex('e-tbar-row', 'Т-тяга', 'T-Bar Row', 'back', ['biceps'], 'barbell',
    'Наклон над Т-грифом, тяните к груди/животу. Сводите лопатки, не округляйте спину.'),
  ex('e-face-pull', 'Face Pull', 'Face Pull', 'shoulders', ['back', 'traps'], 'cable',
    'Канат на уровне лица. Тяните к лицу, локти высоко, кисти разворачивайте наружу.'),
  ex('e-shrug', 'Шраги', 'Shrugs', 'traps', [], 'barbell',
    'Стоя со штангой, поднимайте плечи вверх к ушам. Задержите, опустите. Без круговых движений.'),
  ex('e-db-shrug', 'Шраги с гантелями', 'DB Shrugs', 'traps', [], 'dumbbell',
    'Гантели в руках по бокам. Поднимите плечи вверх, сожмите трапеции, опустите медленно.'),
  ex('e-hyperextension', 'Гиперэкстензия', 'Back Extension', 'back', ['glutes', 'hamstrings'], 'machine',
    'Таз на подушке, скрестите руки. Опуститесь вниз, поднимитесь до прямой линии тела.'),
  ex('e-straight-arm-pd', 'Тяга прямой руки', 'Straight-Arm Pulldown', 'back', [], 'cable',
    'Прямые руки, тяните рукоять дугой к бёдрам. Чувствуйте широчайшие, корпус стабилен.'),
  ex('e-meadows-row', 'Тяга Meadows', 'Meadows Row', 'back', ['biceps'], 'barbell',
    'Гриф в углу, стойка боком. Тяните одной рукой к поясу, локоть назад, корпус почти неподвижен.'),
  // Shoulders
  ex('e-ohp', 'Жим штанги стоя', 'Overhead Press', 'shoulders', ['triceps'], 'barbell',
    'Стоя, штанга у ключиц. Выжмите над головой, голова чуть вперёд вверху. Не прогибайтесь сильно.'),
  ex('e-db-ohp', 'Жим гантелей сидя', 'Seated DB Press', 'shoulders', ['triceps'], 'dumbbell',
    'Сидя, гантели у плеч. Выжмите вверх до почти прямых рук, опустите под контролем.'),
  ex('e-arnold', 'Жим Арнольда', 'Arnold Press', 'shoulders', ['triceps'], 'dumbbell',
    'Гантели перед лицом ладонями к себе. Выжимайте, разворачивая ладони наружу вверху.'),
  ex('e-lateral-raise', 'Махи в стороны', 'Lateral Raise', 'shoulders', [], 'dumbbell',
    'Гантели по бокам, слегка согнутые локти. Поднимите руки в стороны до уровня плеч, опустите.'),
  ex('e-front-raise', 'Махи вперёд', 'Front Raise', 'shoulders', [], 'dumbbell',
    'Поднимите гантели перед собой до уровня плеч. Без раскачки корпусом.'),
  ex('e-rear-delt', 'Махи в наклоне', 'Rear Delt Fly', 'shoulders', [], 'dumbbell',
    'Наклон вперёд, разведите гантели в стороны. Локти мягкие, работа задних дельт.'),
  ex('e-cable-lateral', 'Махи на блоке', 'Cable Lateral Raise', 'shoulders', [], 'cable',
    'Блок снизу, поднимите руку в сторону до параллели с полом. Контролируйте опускание.'),
  ex('e-upright-row', 'Тяга к подбородку', 'Upright Row', 'shoulders', ['traps'], 'barbell',
    'Штанга у бёдер, тяните вверх к подбородку. Локти выше кистей, не задирайте плечи.'),
  ex('e-machine-shoulder', 'Жим плеч в тренажёре', 'Machine Shoulder Press', 'shoulders', ['triceps'], 'machine',
    'Сядьте, рукояти у плеч. Выжмите вверх, не блокируя локти резко, опустите.'),
  ex('e-reverse-pec', 'Обратная бабочка', 'Reverse Pec Deck', 'shoulders', [], 'machine',
    'Лицом к тренажёру, разведите руки назад. Сведите лопатки, работа задних дельт.'),
  // Biceps
  ex('e-bb-curl', 'Подъём штанги на бицепс', 'Barbell Curl', 'biceps', ['forearms'], 'barbell',
    'Стоя, штанга хватом снизу. Согните руки к плечам, локти у корпуса, опустите медленно.'),
  ex('e-db-curl', 'Подъём гантелей на бицепс', 'Dumbbell Curl', 'biceps', ['forearms'], 'dumbbell',
    'Гантели в руках, сгибайте к плечам. Можно с супинацией. Без раскачки.'),
  ex('e-hammer-curl', 'Молотки', 'Hammer Curl', 'biceps', ['forearms'], 'dumbbell',
    'Нейтральный хват (ладони друг к другу). Сгибайте руки, локти неподвижны.'),
  ex('e-preacher', 'Скамья Скотта', 'Preacher Curl', 'biceps', [], 'barbell',
    'Руки на скамье Скотта. Согните штангу/EZ, полностью не разгибайте локти внизу.'),
  ex('e-incline-curl', 'Подъём на наклонной', 'Incline DB Curl', 'biceps', [], 'dumbbell',
    'Лёжа на наклонной скамье. Сгибайте гантели, плечи зафиксированы, растяжение внизу.'),
  ex('e-cable-curl', 'Сгибания на блоке', 'Cable Curl', 'biceps', [], 'cable',
    'Нижний блок, сгибайте рукоять к плечам. Постоянное натяжение, локти на месте.'),
  ex('e-concentration', 'Концентрированные', 'Concentration Curl', 'biceps', [], 'dumbbell',
    'Сидя, локоть у бедра. Сгибайте гантель к плечу, фокус на пике сокращения.'),
  ex('e-ez-curl', 'EZ-штанга на бицепс', 'EZ-Bar Curl', 'biceps', [], 'barbell',
    'EZ-гриф, сгибания к плечам. Хват комфортнее для запястий, локти стабильны.'),
  // Triceps
  ex('e-close-grip', 'Жим узким хватом', 'Close-Grip Bench', 'triceps', ['chest'], 'barbell',
    'Жим лёжа узким хватом. Опустите к нижней груди, выжмите. Локти ближе к корпусу.'),
  ex('e-skull-crusher', 'Французский жим', 'Skull Crusher', 'triceps', [], 'barbell',
    'Лёжа, опустите гриф ко лбу/за голову, разгибая только локти. Плечи неподвижны.'),
  ex('e-triceps-pushdown', 'Разгибания на блоке', 'Triceps Pushdown', 'triceps', [], 'cable',
    'Верхний блок, разогните руки вниз. Локти прижаты, не раскачивайтесь.'),
  ex('e-oh-extension', 'Разгибания из-за головы', 'Overhead Extension', 'triceps', [], 'dumbbell',
    'Гантель/гриф над головой. Согните локти за голову, разогните вверх.'),
  ex('e-dips-tri', 'Брусья (трицепс)', 'Triceps Dips', 'triceps', ['chest'], 'bodyweight',
    'На брусьях корпус вертикальнее. Опуститесь, сгибая локти, выжмите. Акцент на трицепс.'),
  ex('e-kickback', 'Кикбэк', 'Triceps Kickback', 'triceps', [], 'dumbbell',
    'В наклоне, локоть у корпуса. Разогните руку назад до прямой, задержите, верните.'),
  ex('e-rope-pushdown', 'Разгибания канатом', 'Rope Pushdown', 'triceps', [], 'cable',
    'Канат сверху, разгибайте вниз и разводите концы внизу. Локти фиксированы.'),
  // Quads
  ex('e-squat', 'Приседания со штангой', 'Back Squat', 'quads', ['glutes', 'core'], 'barbell',
    'Штанга на трапециях. Приседайте, колени по носкам, грудь вперёд. Встаньте, пятки на полу.'),
  ex('e-front-squat', 'Фронтальные приседания', 'Front Squat', 'quads', ['core'], 'barbell',
    'Штанга на передних дельтах. Локти высоко, приседайте вертикально, корпус прямее.'),
  ex('e-leg-press', 'Жим ногами', 'Leg Press', 'quads', ['glutes'], 'machine',
    'Стопы на платформе. Опустите платформу, сгибая колени, выжмите, не блокируя резко.'),
  ex('e-hack-squat', 'Гакк-приседания', 'Hack Squat', 'quads', ['glutes'], 'machine',
    'Спина на спинке тренажёра. Приседайте до комфортной глубины, выжмите вверх.'),
  ex('e-lunge', 'Выпады', 'Lunges', 'quads', ['glutes'], 'dumbbell',
    'Шаг вперёд или на месте, колено почти до пола. Оттолкнитесь, вернитесь. Чередуйте ноги.'),
  ex('e-walking-lunge', 'Выпады в движении', 'Walking Lunges', 'quads', ['glutes'], 'dumbbell',
    'Шаги вперёд в выпад. Колено над стопой, корпус прямой. Идите контролируемо.'),
  ex('e-leg-extension', 'Разгибания ног', 'Leg Extension', 'quads', [], 'machine',
    'Сядьте, разогните голени до прямых ног. Не дёргайте, опустите медленно.'),
  ex('e-bulgarian', 'Болгарские сплит-приседания', 'Bulgarian Split Squat', 'quads', ['glutes'], 'dumbbell',
    'Задняя нога на скамье. Приседайте на передней, колено по носку, встаньте.'),
  ex('e-goblet', 'Гоблет-приседания', 'Goblet Squat', 'quads', ['glutes', 'core'], 'dumbbell',
    'Гантель/гиря у груди. Приседайте глубоко, локти между колен, спина прямая.'),
  ex('e-leg-press-single', 'Жим одной ногой', 'Single-Leg Press', 'quads', ['glutes'], 'machine',
    'Одна нога на платформе. Жмите, контролируя колено, полная амплитуда без отрыва таза.'),
  // Hamstrings
  ex('e-leg-curl', 'Сгибания ног лёжа', 'Lying Leg Curl', 'hamstrings', [], 'machine',
    'Лёжа, сгибайте голени к ягодицам. Без отрыва бёдер, медленный негатив.'),
  ex('e-seated-curl', 'Сгибания ног сидя', 'Seated Leg Curl', 'hamstrings', [], 'machine',
    'Сидя, сгибайте ноги под валиком. Полная амплитуда, не помогайте корпусом.'),
  ex('e-db-rdl', 'Румынская с гантелями', 'DB RDL', 'hamstrings', ['glutes'], 'dumbbell',
    'Гантели вдоль бёдер. Наклон от бёдер, мягкие колени, встаньте, сжимая ягодицы.'),
  ex('e-good-morning', 'Гудморнинг', 'Good Morning', 'hamstrings', ['back', 'glutes'], 'barbell',
    'Штанга на спине, наклон от бёдер с почти прямыми ногами. Спина нейтральна, встаньте.'),
  ex('e-nordic', 'Nordic curl', 'Nordic Curl', 'hamstrings', [], 'bodyweight',
    'Зафиксируйте голени. Медленно опускайте корпус вперёд, тормозя бицепсом бедра, поднимитесь.'),
  // Glutes
  ex('e-hip-thrust', 'Ягодичный мост', 'Hip Thrust', 'glutes', ['hamstrings'], 'barbell',
    'Верх спины на скамье, штанга на бёдрах. Поднимите таз до прямой линии, сожмите ягодицы.'),
  ex('e-glute-bridge', 'Мостик', 'Glute Bridge', 'glutes', [], 'bodyweight',
    'Лёжа, стопы на полу. Поднимите таз, сожмите ягодицы вверху, опустите.'),
  ex('e-cable-kickback', 'Отведения на блоке', 'Cable Kickback', 'glutes', [], 'cable',
    'Блок снизу у лодыжки. Отведите ногу назад, не прогибаясь в пояснице.'),
  ex('e-abduction', 'Отведения ног', 'Hip Abduction', 'glutes', [], 'machine',
    'В тренажёре разведите бёдра наружу против сопротивления. Контролируемое сведение.'),
  ex('e-step-up', 'Зашагивания', 'Step-up', 'glutes', ['quads'], 'dumbbell',
    'Зашагните на тумбу рабочей ногой, встаньте полностью, спуститесь под контролем.'),
  // Calves
  ex('e-standing-calf', 'Подъёмы на носки стоя', 'Standing Calf Raise', 'calves', [], 'machine',
    'Стоя, поднимитесь на носки максимально высоко, опуститесь с растяжением.'),
  ex('e-seated-calf', 'Подъёмы на носки сидя', 'Seated Calf Raise', 'calves', [], 'machine',
    'Сидя, поднимайте носки вверх. Акцент на камбаловидную, полная амплитуда.'),
  ex('e-leg-press-calf', 'Икры в жиме ногами', 'Leg Press Calf', 'calves', [], 'machine',
    'В жиме ногами только голеностоп: носки на краю, подъём и опускание на носки.'),
  ex('e-db-calf', 'Икры с гантелью', 'DB Calf Raise', 'calves', [], 'dumbbell',
    'Гантель в руке, подъём на носок одной ноги. Пауза вверху, медленный спуск.'),
  // Core
  ex('e-plank', 'Планка', 'Plank', 'core', [], 'bodyweight',
    'Упор на предплечья, тело в линию. Держите, не поднимая таз и не провисая.'),
  ex('e-crunch', 'Скручивания', 'Crunch', 'core', [], 'bodyweight',
    'Лёжа, скрутите верх корпуса к тазу. Поясница на полу, без рывков за голову.'),
  ex('e-hanging-leg', 'Подъём ног в висе', 'Hanging Leg Raise', 'core', [], 'bodyweight',
    'В висе поднимите прямые или согнутые ноги. Без сильного раскачивания, опустите медленно.'),
  ex('e-cable-crunch', 'Скручивания на блоке', 'Cable Crunch', 'core', [], 'cable',
    'На коленях, канат у головы. Скручивайте корпус вниз, сгибая позвоночник.'),
  ex('e-ab-wheel', 'Ролик для пресса', 'Ab Wheel', 'core', [], 'other',
    'С колен, выкатайте ролик вперёд, сохраняя пресс, вернитесь, не проваливаясь в поясницу.'),
  ex('e-russian-twist', 'Русские скручивания', 'Russian Twist', 'core', [], 'bodyweight',
    'Сидя, корпус отклонён. Поворачивайте корпус в стороны, ноги стабильны.'),
  ex('e-dead-bug', 'Dead Bug', 'Dead Bug', 'core', [], 'bodyweight',
    'На спине, руки вверх, ноги согнуты. Поочерёдно выпрямляйте противоположные руку и ногу, поясница прижата.'),
  ex('e-pallof', 'Pallof Press', 'Pallof Press', 'core', [], 'cable',
    'Блок сбоку, выжмите руки вперёд и удерживайте. Не давайте корпусу развернуться.'),
  // Forearms
  ex('e-wrist-curl', 'Сгибания запястий', 'Wrist Curl', 'forearms', [], 'barbell',
    'Предплечья на бёдрах или скамье, сгибайте запястья вверх. Медленный негатив.'),
  ex('e-farmer-walk', 'Прогулка фермера', "Farmer's Walk", 'forearms', ['traps', 'core'], 'dumbbell',
    'Тяжёлые гантели/гири в руках, идите короткими шагами. Плечи вниз, корпус прямой, не раскачивайтесь.'),
  ex('e-reverse-curl', 'Обратные сгибания', 'Reverse Curl', 'forearms', ['biceps'], 'barbell',
    'Хват сверху, сгибайте штангу. Локти у корпуса, работают предплечья и бицепс.'),
  // Full body / Olympic-ish
  ex('e-clean', 'Подъём на грудь', 'Power Clean', 'full_body', ['traps', 'glutes'], 'barbell',
    'С пола или виса: подрыв и подсед, штанга на передние дельты. Встаньте. Техника важнее веса.'),
  ex('e-snatch-grip-dl', 'Тяга широким хватом', 'Snatch-Grip DL', 'back', ['hamstrings'], 'barbell',
    'Широкий хват, становая. Спина жёсткая, штанга близко, полный разгиб вверху.'),
  ex('e-thruster', 'Трастеры', 'Thruster', 'full_body', ['shoulders', 'quads'], 'barbell',
    'Фронтальный присед и жим: вставая из приседа, выжмите штангу над головой одним движением.'),
  ex('e-kb-swing', 'Махи гирей', 'Kettlebell Swing', 'glutes', ['hamstrings', 'core'], 'kettlebell',
    'Гиря между ног, мах до уровня груди за счёт бёдер, не руками. Спина прямая.'),
  ex('e-burpee', 'Бёрпи', 'Burpee', 'full_body', [], 'bodyweight',
    'Упор лёжа, отжимание по желанию, прыжок вверх. Держите ритм, приземляйтесь мягко.'),
  // More variety
  ex('e-incline-fly', 'Разведение наклон', 'Incline Fly', 'chest', [], 'dumbbell',
    'Наклонная скамья, разведение гантелей по дуге. Мягкие локти, растяжение внизу.'),
  ex('e-floor-press', 'Жим с пола', 'Floor Press', 'chest', ['triceps'], 'barbell',
    'Лёжа на полу, жмите штангу или гантели. Амплитуда короче — локти касаются пола.'),
  ex('e-pendlay', 'Тяга Пендли', 'Pendlay Row', 'back', ['biceps'], 'barbell',
    'Штанга с пола каждый повтор. Взрывная тяга к поясу в наклоне, спина параллельна полу.'),
  ex('e-chest-supported-row', 'Тяга с упором', 'Chest-Supported Row', 'back', ['biceps'], 'dumbbell',
    'Грудь на скамье, тяните гантели вверх. Без читинга корпусом, сводите лопатки.'),
  ex('e-y-raise', 'Y-подъёмы', 'Y-Raise', 'shoulders', [], 'dumbbell',
    'Лёжа или в наклоне, поднимайте руки в форме Y. Лёгкий вес, контроль задних дельт.'),
  ex('e-lu-raise', 'Lu Raises', 'Lu Raises', 'shoulders', [], 'dumbbell',
    'Дуговые подъёмы гантелей вокруг тела в плоскости плеч. Плавно, без рывков.'),
  ex('e-spider-curl', 'Паучьи сгибания', 'Spider Curl', 'biceps', [], 'dumbbell',
    'Грудь на наклонной, руки свисают. Сгибайте гантели, пиковое сокращение вверху.'),
  ex('e-jm-press', 'JM Press', 'JM Press', 'triceps', ['chest'], 'barbell',
    'Между жимом узким и французским: опускайте гриф к шее, разгибайте локти.'),
  ex('e-overhead-cable', 'Разгибания на блоке сверху', 'Cable Overhead Ext', 'triceps', [], 'cable',
    'Спиной к блоку, разгибайте руки из-за головы. Локти вверх, трицепс под нагрузкой.'),
  ex('e-sissy-squat', 'Сисси-приседания', 'Sissy Squat', 'quads', [], 'bodyweight',
    'Пятки приподняты, отводите колени вперёд, корпус назад. Квадрицепс, баланс важен.'),
  ex('e-belt-squat', 'Приседания с поясом', 'Belt Squat', 'quads', ['glutes'], 'machine',
    'Пояс с отягощением, приседайте. Нагрузка на ноги, меньше осевой на позвоночник.'),
  ex('e-leg-curl-standing', 'Сгибания стоя', 'Standing Leg Curl', 'hamstrings', [], 'machine',
    'Стоя, сгибайте голень одной ноги. Корпус стабилен, полная амплитуда.'),
  ex('e-45-hyper', 'Гипер 45°', '45° Hyper', 'glutes', ['hamstrings', 'back'], 'machine',
    'На 45° гиперэкстензии поднимайте корпус, акцент на ягодицы. Не переразгибайтесь.'),
  ex('e-donkey-calf', 'Икры «осёл»', 'Donkey Calf Raise', 'calves', [], 'machine',
    'Наклон вперёд, подъём на носки. Растяжение внизу, пик вверху.'),
  ex('e-side-plank', 'Боковая планка', 'Side Plank', 'core', [], 'bodyweight',
    'На боку, упор на предплечье. Тело в линию, таз не опускайте. Держите.'),
  ex('e-hanging-knee', 'Колени к груди', 'Hanging Knee Raise', 'core', [], 'bodyweight',
    'В висе подтягивайте колени к груди. Без раскачки, опускайте медленно.'),
  ex('e-machine-row', 'Тяга в тренажёре', 'Machine Row', 'back', ['biceps'], 'machine',
    'Сядьте в тренажёр, тяните рукояти к себе. Сводите лопатки, грудь вперёд.'),
  ex('e-smith-squat', 'Приседания в Смите', 'Smith Squat', 'quads', ['glutes'], 'machine',
    'В Смите приседайте по направляющим. Контроль глубины, колени по носкам.'),
  ex('e-smith-bench', 'Жим в Смите', 'Smith Bench Press', 'chest', ['triceps'], 'machine',
    'Жим лёжа в Смите. Опустите к груди, выжмите. Траектория фиксирована.'),
  ex('e-cable-row-single', 'Тяга одной рукой', 'Single-Arm Cable Row', 'back', ['biceps'], 'cable',
    'Одной рукой тяните блок к поясу. Корпус стабилен, лопатка работает.'),
  ex('e-pec-deck-reverse', 'Пек-дек обратный', 'Reverse Fly Machine', 'shoulders', [], 'machine',
    'Обратная бабочка: разведите руки назад. Задние дельты, без рывка веса.'),
  ex('e-trap-bar-dl', 'Тяга с трэп-грифом', 'Trap Bar Deadlift', 'back', ['quads', 'glutes'], 'barbell',
    'Встаньте внутри трэп-грифа, поднимите, разгибая ноги и бёдра. Нейтральный хват.'),
  ex('e-zercher', 'Зерхер-приседания', 'Zercher Squat', 'quads', ['core', 'back'], 'barbell',
    'Штанга в сгибах локтей. Приседайте, локти у корпуса, спина прямая.'),
  ex('e-box-squat', 'Приседания на ящик', 'Box Squat', 'quads', ['glutes'], 'barbell',
    'Присед на ящик до касания. Пауза по желанию, встаньте взрывно. Контроль посадки.'),
  ex('e-pause-squat', 'Приседания с паузой', 'Pause Squat', 'quads', ['glutes'], 'barbell',
    'В нижней точке пауза 1–3 с без расслабления. Встаньте мощно.'),
  ex('e-pin-press', 'Жим с пинтов', 'Pin Press', 'chest', ['triceps'], 'barbell',
    'Жим с упоров с мёртвой точки. Сорвите гриф и выжмите.'),
  ex('e-spoto-press', 'Spoto Press', 'Spoto Press', 'chest', ['triceps'], 'barbell',
    'Жим лёжа с остановкой грифа за 2–5 см до груди. Без касания, выжмите.'),
  ex('e-deficit-dl', 'Тяга с дефицита', 'Deficit Deadlift', 'back', ['hamstrings'], 'barbell',
    'Стоя на возвышении, становая с увеличенной амплитудой. Спина жёсткая.'),
  ex('e-block-pull', 'Тяга с блоков', 'Block Pull', 'back', ['traps'], 'barbell',
    'Штанга на блоках. Тяга с высокой точки, акцент на лок и верх спины.'),
  ex('e-seal-row', 'Seal Row', 'Seal Row', 'back', ['biceps'], 'barbell',
    'Лёжа лицом вниз на скамье, тяните штангу с пола. Чистый изолятор спины.'),
  ex('e-zottman', 'Сгибания Зоттмана', 'Zottman Curl', 'biceps', ['forearms'], 'dumbbell',
    'Сгиб ладонями вверх, вверху разворот, опускание хватом сверху. Бицепс и предплечья.'),
  ex('e-bayesian-curl', 'Bayesian curl', 'Bayesian Curl', 'biceps', [], 'cable',
    'Блок сзади, рука отведена. Сгибайте, растягивая длинную головку бицепса.'),
  ex('e-crossbody-ext', 'Разгибания кроссбоди', 'Cross-body Extension', 'triceps', [], 'cable',
    'Разгибание через тело на блоке. Локоть фиксирован, полная амплитуда.'),
  ex('e-hack-deadlift', 'Гакк-тяга', 'Hack Lift', 'quads', ['back'], 'machine',
    'В гакк-тренажёре тяговое движение ногами. Спина по инструкции тренажёра.'),
  ex('e-adductor', 'Сведения ног', 'Hip Adduction', 'glutes', [], 'machine',
    'В тренажёре сводите бёдра внутрь. Контроль, без рывков.'),
  ex('e-tibialis', 'Подъёмы носков на себя', 'Tibialis Raise', 'calves', [], 'other',
    'Поднимайте носки на себя у стены или с весом. Медленно, полная амплитуда.'),
  ex('e-neck-curl', 'Сгибания шеи', 'Neck Curl', 'traps', [], 'other',
    'Сгибайте шею с очень малым весом. Плавно, без рывков.'),
  ex('e-suitcase-carry', 'Чемодан', 'Suitcase Carry', 'core', ['forearms'], 'dumbbell',
    'Гантель в одной руке, идите ровно. Не наклоняйтесь к весу, кор в напряжении.'),
  ex('e-sledgehammer', 'Удары кувалдой', 'Sledgehammer', 'full_body', ['core'], 'other',
    'Удары кувалдой по покрышке. Ноги и корпус включайте, чередуйте стороны.'),
  ex('e-battle-ropes', 'Канаты', 'Battle Ropes', 'full_body', ['shoulders'], 'other',
    'Волны канатами поочерёдно или вместе. Корпус стабилен, ритм высокий.'),
  ex('e-sled-push', 'Толкание саней', 'Sled Push', 'quads', ['glutes', 'full_body'], 'other',
    'Толкайте сани в наклоне. Короткие шаги, руки жёсткие, ноги мощно упираются.'),
  ex('e-sled-pull', 'Тяга саней', 'Sled Pull', 'back', ['hamstrings'], 'other',
    'Тяните сани канатом или спиной назад. Шаги назад, спина прямая.'),
  ex('e-box-jump', 'Запрыгивания', 'Box Jump', 'quads', ['glutes'], 'bodyweight',
    'Прыжок на тумбу двумя ногами, мягкое приземление. Спрыгивайте осторожно.'),
  ex('e-jump-squat', 'Прыжковые приседания', 'Jump Squat', 'quads', ['glutes'], 'bodyweight',
    'Присед и взрывной прыжок вверх. Мягкое приземление сразу в следующий присед.'),
  ex('e-inverted-row', 'Австралийские подтягивания', 'Inverted Row', 'back', ['biceps'], 'bodyweight',
    'Под грифом, тело прямое, тянитесь грудью к грифу. Пятки на полу.'),
  ex('e-diamond-pushup', 'Алмазные отжимания', 'Diamond Push-up', 'triceps', ['chest'], 'bodyweight',
    'Кисти вместе ромбом. Отжимания, локти вдоль — акцент на трицепс.'),
  ex('e-pike-pushup', 'Отжимания уголком', 'Pike Push-up', 'shoulders', ['triceps'], 'bodyweight',
    'Таз вверх домиком, опустите голову между руками, выжмите. Плечи.'),
  ex('e-band-pullapart', 'Разведения резиной', 'Band Pull-apart', 'shoulders', ['back'], 'band',
    'Резинка перед собой, разведите руки в стороны, сведите лопатки. Медленно верните.'),
  ex('e-band-row', 'Тяга с резиной', 'Band Row', 'back', ['biceps'], 'band',
    'Резинка закреплена впереди. Тяните к поясу, локти назад, корпус стабилен.'),
  ex('e-kb-goblet', 'Гоблет с гирей', 'KB Goblet Squat', 'quads', ['glutes', 'core'], 'kettlebell',
    'Гиря у груди, приседайте глубоко. Локти между колен, пятки на полу.'),
  ex('e-kb-press', 'Жим гири', 'KB Press', 'shoulders', ['triceps'], 'kettlebell',
    'Гиря у плеча, выжмите над головой. Запястье прямое, корпус не заваливается.'),
  ex('e-kb-row', 'Тяга гири', 'KB Row', 'back', ['biceps'], 'kettlebell',
    'В наклоне тяните гирю к поясу. Лопатка к позвоночнику, без скручивания.'),
  ex('e-machine-fly', 'Сведения в тренажёре', 'Machine Fly', 'chest', [], 'machine',
    'В тренажёре сведите рукояти перед грудью. Мягкие локти, растяжение в стороны.'),
  ex('e-smith-ohp', 'Жим стоя в Смите', 'Smith OHP', 'shoulders', ['triceps'], 'machine',
    'Жим стоя или сидя в Смите. Выжмите гриф вверх по направляющим, опустите к плечам.'),
  ex('e-vbar-pulldown', 'Тяга V-грифа', 'V-Bar Pulldown', 'back', ['biceps'], 'cable',
    'V-гриф сверху, тяните к верхней груди. Узкий хват, локти вниз.'),
  ex('e-straight-bar-pd', 'Тяга прямой рукояти', 'Straight Bar Pulldown', 'back', ['biceps'], 'cable',
    'Прямая рукоять, тяга сверху к груди. Контроль, без сильного отклонения назад.'),
  ex('e-ez-skull', 'Французский с EZ', 'EZ Skull Crusher', 'triceps', [], 'barbell',
    'EZ-гриф, французский жим лёжа. Опустите за голову или ко лбу, разогните локти.'),
  ex('e-decline-crunch', 'Скручивания на наклоне', 'Decline Crunch', 'core', [], 'bodyweight',
    'На наклонной головой вниз, скручивайте корпус вверх. Без рывка за шею.'),
  ex('e-toes-to-bar', 'Носки к перекладине', 'Toes-to-Bar', 'core', [], 'bodyweight',
    'В висе поднимите носки к перекладине. Контроль, можно с согнутыми коленями.'),
  ex('e-glute-ham', 'GHD', 'Glute-Ham Raise', 'hamstrings', ['glutes'], 'machine',
    'На GHD: от бёдер опуститесь и поднимитесь, сгибая колени. Ягодицы и бицепс бедра.'),
  // Band — ноги и ягодицы
  ex(
    'e-band-squat',
    'Приседания с резинкой',
    'Band Squat',
    'quads',
    ['glutes'],
    'band',
    'Встаньте на середину резинки, концы держите у плеч. Приседайте до параллели бёдер, колени наружу, спина прямая. Встаньте, преодолевая сопротивление.'
  ),
  ex(
    'e-band-squat-knees',
    'Приседания с резинкой над коленями',
    'Band Squat (above knees)',
    'glutes',
    ['quads'],
    'band',
    'Резинку наденьте чуть выше колен. Приседайте, активно разводя колени наружу против сопротивления. Не сводите колени внутрь.'
  ),
  ex(
    'e-band-glute-bridge',
    'Ягодичный мостик с резинкой',
    'Band Glute Bridge',
    'glutes',
    ['hamstrings'],
    'band',
    'Лёжа на спине, резинка над коленями, стопы на полу. Поднимите таз вверх, сожмите ягодицы вверху, опуститесь контролируемо.'
  ),
  ex(
    'e-band-bridge-abduction',
    'Ягодичный мостик с разведением коленей',
    'Band Bridge with Knee Abduction',
    'glutes',
    [],
    'band',
    'В верхней точке мостика разведите колени наружу против резинки, сведите и опустите таз. Держите корпус стабильным.'
  ),
  ex(
    'e-band-rdl',
    'Румынская тяга с резинкой',
    'Band Romanian Deadlift',
    'hamstrings',
    ['glutes', 'back'],
    'band',
    'Встаньте на резинку, рукояти в руках. С мягкими коленями наклонитесь вперёд от бёдер, затем выпрямитесь, натягивая резинку. Спина нейтральна.'
  ),
  ex(
    'e-band-reverse-lunge',
    'Выпады назад с резинкой',
    'Band Reverse Lunge',
    'glutes',
    ['quads'],
    'band',
    'Резинка под передней ногой, концы в руках. Шагните назад, опустите колено почти до пола, вернитесь в стойку. Чередуйте ноги.'
  ),
  ex(
    'e-band-forward-lunge',
    'Выпады вперёд с резинкой',
    'Band Forward Lunge',
    'quads',
    ['glutes'],
    'band',
    'Встаньте на резинку или закрепите её. Шаг вперёд, колено над стопой, опуститесь в выпад и оттолкнитесь обратно.'
  ),
  ex(
    'e-band-lateral-walk',
    'Боковые шаги с резинкой',
    'Band Lateral Walk',
    'glutes',
    [],
    'band',
    'Резинка над коленями или на щиколотках. Полуприсед, шаги в сторону с постоянным натяжением. Не «прыгайте» ногами.'
  ),
  ex(
    'e-band-kickback',
    'Отведение ноги назад с резинкой',
    'Band Glute Kickback',
    'glutes',
    [],
    'band',
    'Резинка на щиколотках. Стоя на одной ноге, отведите другую назад, сжимая ягодицу. Корпус не раскачивайте.'
  ),
  ex(
    'e-band-side-leg-raise',
    'Отведение ноги в сторону с резинкой',
    'Band Side Leg Raise',
    'glutes',
    [],
    'band',
    'Резинка на щиколотках. Отведите ногу в сторону против сопротивления, медленно верните. Корпус держите прямо.'
  ),
  // Band — спина и плечи
  ex(
    'e-band-seated-row',
    'Тяга резинки к поясу сидя',
    'Band Seated Row',
    'back',
    ['biceps'],
    'band',
    'Сидя, резинку зацепите за стопы. Тяните к поясу, сводя лопатки, локти вдоль корпуса. Плавно выпрямите руки.'
  ),
  ex(
    'e-band-bent-row',
    'Тяга резинки в наклоне',
    'Band Bent-Over Row',
    'back',
    ['shoulders'],
    'band',
    'Встаньте на резинку, наклон от бёдер. Тяните к низу груди/поясу, локти назад. Не округляйте поясницу.'
  ),
  ex(
    'e-band-single-row',
    'Тяга резинки одной рукой',
    'Band Single-Arm Row',
    'back',
    ['biceps'],
    'band',
    'Закрепите резинку впереди/снизу. Тяните одной рукой к поясу, лопатку к позвоночнику. Смените сторону.'
  ),
  ex(
    'e-band-rear-delt-fly',
    'Разведение рук с резинкой',
    'Band Rear Delt Fly',
    'shoulders',
    ['back'],
    'band',
    'Держите резинку перед собой. Разведите руки в стороны и назад, сводя лопатки. Работают задние дельты.'
  ),
  ex(
    'e-band-face-pull',
    'Face pull с резинкой',
    'Band Face Pull',
    'shoulders',
    ['traps', 'back'],
    'band',
    'Резинку на уровне лица. Тяните к лицу, локти высоко, кисти разворачивайте наружу. Контролируйте возврат.'
  ),
  ex(
    'e-band-oh-press',
    'Жим резинки над головой',
    'Band Overhead Press',
    'shoulders',
    ['triceps'],
    'band',
    'Встаньте на резинку, рукояти у плеч. Выжмите руки вверх над головой, не прогибаясь в пояснице. Опустите медленно.'
  ),
  ex(
    'e-band-front-raise',
    'Подъём рук перед собой',
    'Band Front Raise',
    'shoulders',
    [],
    'band',
    'Встаньте на резинку. Поднимите прямые руки перед собой до уровня плеч, опустите под контролем.'
  ),
  ex(
    'e-band-lateral-raise',
    'Разведение рук в стороны',
    'Band Lateral Raise',
    'shoulders',
    [],
    'band',
    'Встаньте на резинку. Разведите руки в стороны до параллели с полом, слегка согнутые локти. Не раскачивайтесь.'
  ),
  ex(
    'e-band-upright-row',
    'Тяга резинки к подбородку',
    'Band Upright Row',
    'shoulders',
    ['traps'],
    'band',
    'Встаньте на резинку. Тяните вверх к подбородку, локти выше кистей. Не поднимайте плечи к ушам чрезмерно.'
  ),
  ex(
    'e-band-pullover',
    'Пуловер с резинкой',
    'Band Pullover',
    'back',
    ['chest'],
    'band',
    'Закрепите резинку высоко сзади. Прямыми руками проведите дугу от над головой к бёдрам, растягивая широчайшие.'
  ),
  // Band — грудь и руки
  ex(
    'e-band-chest-press',
    'Жим резинки от груди стоя',
    'Band Chest Press',
    'chest',
    ['triceps'],
    'band',
    'Резинку за спиной на уровне груди. Выжмите руки вперёд до выпрямления, сведите грудь. Верните локти назад.'
  ),
  ex(
    'e-band-push-up',
    'Отжимания с резинкой',
    'Band Push-up',
    'chest',
    ['shoulders', 'triceps'],
    'band',
    'Резинку через верх спины, концы под ладонями. Отжимайтесь, преодолевая доп. сопротивление на подъёме.'
  ),
  ex(
    'e-band-chest-fly',
    'Сведение рук перед собой с резинкой',
    'Band Chest Fly',
    'chest',
    [],
    'band',
    'Резинка за спиной. С мягкими локтями сведите руки перед грудью, как в сведении. Медленно разведите.'
  ),
  ex(
    'e-band-oh-triceps',
    'Разгибание рук с резинкой над головой',
    'Band Overhead Triceps Extension',
    'triceps',
    [],
    'band',
    'Встаньте на резинку или держите её за спиной. Руки над головой, разогните локти вверх, не разводя локти в стороны.'
  ),
  ex(
    'e-band-kickback-tri',
    'Разгибание руки назад в наклоне',
    'Band Triceps Kickback',
    'triceps',
    [],
    'band',
    'В наклоне, локоть прижат к корпусу. Разогните руку назад до полного выпрямления, задержите и верните.'
  ),
  ex(
    'e-band-biceps-curl',
    'Сгибание рук на бицепс с резинкой',
    'Band Biceps Curl',
    'biceps',
    [],
    'band',
    'Встаньте на резинку, хват ладонями вверх. Согните руки к плечам, локти у корпуса. Опустите медленно.'
  ),
  ex(
    'e-band-hammer-curl',
    'Молотковые сгибания с резинкой',
    'Band Hammer Curl',
    'biceps',
    ['forearms'],
    'band',
    'Встаньте на резинку, нейтральный хват (ладони друг к другу). Сгибайте руки, не разворачивая кисти.'
  ),
  // Band — пресс и корпус
  ex(
    'e-band-crunch',
    'Скручивания с резинкой',
    'Band Crunch',
    'core',
    [],
    'band',
    'Лёжа, резинку держите над головой или закрепите сзади. Скручивайтесь, подтягивая грудь к тазу, поясница на полу.'
  ),
  ex(
    'e-band-torso-twist',
    'Повороты корпуса с резинкой',
    'Band Torso Twist',
    'core',
    [],
    'band',
    'Стоя или сидя, держите резинку перед собой. Поворачивайте корпус в стороны, бёдра стабильны. Работают косые.'
  ),
  ex(
    'e-band-pallof',
    'Pallof press (анти-ротация)',
    'Band Pallof Press',
    'core',
    [],
    'band',
    'Резинка сбоку на уровне груди. Выжмите руки вперёд и удерживайте, не давая корпусу развернуться. Смените сторону.'
  ),
]

function buildRoutines(): Routine[] {
  const now = Date.now()
  return [
    {
      id: 'r-ppl',
      name: 'PPL (Push / Pull / Legs)',
      template: 'ppl',
      createdAt: now,
      days: [
        {
          name: 'Push',
          exerciseIds: [
            'e-bench-press',
            'e-ohp',
            'e-db-incline',
            'e-lateral-raise',
            'e-triceps-pushdown',
            'e-oh-extension',
          ],
        },
        {
          name: 'Pull',
          exerciseIds: [
            'e-deadlift',
            'e-pull-up',
            'e-barbell-row',
            'e-face-pull',
            'e-bb-curl',
            'e-hammer-curl',
          ],
        },
        {
          name: 'Legs',
          exerciseIds: [
            'e-squat',
            'e-rdl',
            'e-leg-press',
            'e-leg-curl',
            'e-leg-extension',
            'e-standing-calf',
          ],
        },
      ],
    },
    {
      id: 'r-ul',
      name: 'Upper / Lower',
      template: 'upper_lower',
      createdAt: now,
      days: [
        {
          name: 'Upper A',
          exerciseIds: [
            'e-bench-press',
            'e-barbell-row',
            'e-ohp',
            'e-lat-pulldown',
            'e-lateral-raise',
            'e-bb-curl',
            'e-triceps-pushdown',
          ],
        },
        {
          name: 'Lower A',
          exerciseIds: [
            'e-squat',
            'e-rdl',
            'e-leg-press',
            'e-leg-curl',
            'e-standing-calf',
            'e-plank',
          ],
        },
        {
          name: 'Upper B',
          exerciseIds: [
            'e-db-incline',
            'e-pull-up',
            'e-db-ohp',
            'e-seated-row',
            'e-rear-delt',
            'e-hammer-curl',
            'e-skull-crusher',
          ],
        },
        {
          name: 'Lower B',
          exerciseIds: [
            'e-deadlift',
            'e-front-squat',
            'e-bulgarian',
            'e-hip-thrust',
            'e-seated-calf',
            'e-hanging-leg',
          ],
        },
      ],
    },
    {
      id: 'r-pp',
      name: 'Push / Pull',
      template: 'push_pull',
      createdAt: now,
      days: [
        {
          name: 'Push',
          exerciseIds: [
            'e-bench-press',
            'e-ohp',
            'e-db-fly',
            'e-lateral-raise',
            'e-dips-tri',
            'e-triceps-pushdown',
          ],
        },
        {
          name: 'Pull',
          exerciseIds: [
            'e-pull-up',
            'e-barbell-row',
            'e-rdl',
            'e-face-pull',
            'e-bb-curl',
            'e-shrug',
          ],
        },
      ],
    },
    {
      id: 'r-fb',
      name: 'Full Body 3×',
      template: 'full_body',
      createdAt: now,
      days: [
        {
          name: 'Full A',
          exerciseIds: [
            'e-squat',
            'e-bench-press',
            'e-barbell-row',
            'e-ohp',
            'e-rdl',
            'e-plank',
          ],
        },
        {
          name: 'Full B',
          exerciseIds: [
            'e-deadlift',
            'e-db-incline',
            'e-pull-up',
            'e-lunge',
            'e-lateral-raise',
            'e-hanging-leg',
          ],
        },
        {
          name: 'Full C',
          exerciseIds: [
            'e-front-squat',
            'e-ohp',
            'e-seated-row',
            'e-hip-thrust',
            'e-dips-chest',
            'e-bb-curl',
          ],
        },
      ],
    },
  ]
}

/** Bump when built-in SEED_FOODS / SEED_EXERCISES catalogs change so existing DBs get updates. */
export const SEED_VERSION = 6

export async function ensureSeeded(): Promise<void> {
  const settings = await db.settings.get('main')
  if (!settings) {
    await db.settings.put(DEFAULT_SETTINGS)
  }

  const current = (await db.settings.get('main'))!
  const applied = current.seedVersion ?? 0

  // Empty tables (first install) or catalog version bump for existing users.
  // Custom (user-created) foods/exercises are preserved.
  if (applied < SEED_VERSION) {
    const customFoods = await db.foods.filter((f) => f.isCustom).toArray()
    await db.foods.clear()
    await db.foods.bulkPut([...SEED_FOODS, ...customFoods])

    const customExercises = await db.exercises.filter((e) => e.isCustom).toArray()
    await db.exercises.clear()
    await db.exercises.bulkPut([...SEED_EXERCISES, ...customExercises])

    await db.settings.update('main', { seedVersion: SEED_VERSION })
  } else {
    // Safety: if somehow emptied after version stamp, refill built-ins only.
    if ((await db.foods.count()) === 0) {
      await db.foods.bulkPut(SEED_FOODS)
    }
    if ((await db.exercises.count()) === 0) {
      await db.exercises.bulkPut(SEED_EXERCISES)
    }
  }

  const routineCount = await db.routines.count()
  if (routineCount === 0) {
    await db.routines.bulkPut(buildRoutines())
  }
}
